package com.rw.service.redpoint;

/**
 * 红点类型枚举(最好使用客户端的配置表)
 * 
 * @author Jamaz
 *
 */
public enum RedPointType {
	NONE,
	HOME_TOP_WINDOW_MAINCITY,
	HOME_TOP_WINDOW_GROUP,
	HOME_TOP_WINDOW_AREA,
	HOME_WINDOW_HERO,
	HERO_LIST_WINDOW_ROLE,
	HERO_LIST_WINDOW_ROLE_SUMMON,
	ROLE_WINDOW_UPGRADE_STAR,
	ROLE_WINDOW_DRESS_EQUIP,
	ROLE_WINDOW_ADVANCED,
	HOME_WINDOW_FISHING_STAGE,
	FISHING_WINDOW_LOW_LEVEL,
	FISHING_WINDOW_MIDDLE_LEVEL,
	HOME_WINDOW_TASK,
	HOME_WINDOW_DAILY,
	HOME_WINDOW_SIGN_IN,
	HOME_WINWOW_MAIL,
	HOME_WINDOW_SEVER_GIFT,
	HOME_WINDOW_OPEN_GIGT,
	HOME_WINDOW_FRIEND,
	FRIEND_WINDOW_RECEIVE_POWER,
	FRIEND_WINDOW_ADD_FRIEND,
	HOME_WINDOW_STORE,
	HOME_WINDOW_CHAT,
	CHAT_WINDOW_PRIVATE_CHAT,
	HOME_WINDOW_ARENA,
	PVP_ENTRY_WINDOW_ARENA,
	ARENA_WINDOW_BATTLE_LOG,
	ARENA_WINDOW_SUM_POINT,
	ARENA_WINDOW_RANK_REWARD_POINT,
	HOME_WINDOW_GROUP,
	GROUP_WINDOW_SKILL_LEARN,
	GROUP_WINDOW_MANAGER,
	GROUP_WINDOW_MANAGER_ENTER_GROUP,
	HOME_WINDOW_PVE,
	PVE_WINDOW_BATTLE_TOWER,
	BATTLE_TOWER_WINDOW_OPEN_CHEST,
	HOME_WINDOW_ACTIVITY,
	GM_FEEDBACK,
	HOME_WINDOW_FIX_EQUIP,
	FIX_EQUIP_HERO_LIST,
	FIX_EQUIP_LIST,
	HERO_FIX_EQUIP_QUALITY_UP,
	HERO_FIX_EQUIP_START_UP,
	GROUP_SECRET_ENTRY,
	GROUP_SECRET_RES_REWARD,
	GROUP_SECRET_RECORD_KEY,
	MAGIC_SECRET_SCORE_REWARD,
	BATTLE_TOWER_SWEEP_END,
	PVE_MAGIC_SECRET_SCORE_REWARD,
	TEAMBATTLE_FULL_MEMBER,
	PVE_TEAMBATTLE,
	FORTUNE_CAT,
	LIMIT_HERO,
	LIMIT_HERO_Buy_One,
	HOME_WINDOW_PEAK_ARENA,
	PEAK_ARENA_SCORE_REWARD,
	HOME_TOP_FIGHTING_GROWTH,
	HOME_WINDOW_ITEM_BAG,
	ITEM_BAG_ALL_BTN,
	ITEM_BAG_CONSUME_BTN,
	HOME_WINDOW_RANKING,
	RANKING_ARENA_LIST,
	RANKING_ARENA_CHAMPION,
	GROUP_SECRET_ADVENTURE,
	EVIL_BAO_ARRIVE,
	GROUP_SECRET_ROB,
	MAGIC_SECRET_SWEEP,
	TEAMBATLE_CANCHALLENGE,
	PVE_TREASURE_LAND,
	PVE_TRAINING_VALLEY,
	PVE_SURVIVAL_LAND,
	BATTLE_TOWER_NEW_BOSS;

	private RedPointType() {

	}

	public RedPointType getEnumByInt(int id) {
		RedPointType redPointType = null;
		for (RedPointType eNum : values()) {
			if (eNum.ordinal() == id) {
				redPointType = eNum;
				break;
			}
		}
		return redPointType;
	}

}
