// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DailyGif.proto

package com.rwproto;

public final class DailyGifProtos {
  private DailyGifProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code EType}
   */
  public enum EType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>InfoMsg = 0;</code>
     *
     * <pre>
     *������Ϣ
     * </pre>
     */
    InfoMsg(0, 0),
    /**
     * <code>GetGif = 1;</code>
     *
     * <pre>
     *��ȡ���
     * </pre>
     */
    GetGif(1, 1),
    ;

    /**
     * <code>InfoMsg = 0;</code>
     *
     * <pre>
     *������Ϣ
     * </pre>
     */
    public static final int InfoMsg_VALUE = 0;
    /**
     * <code>GetGif = 1;</code>
     *
     * <pre>
     *��ȡ���
     * </pre>
     */
    public static final int GetGif_VALUE = 1;


    public final int getNumber() { return value; }

    public static EType valueOf(int value) {
      switch (value) {
        case 0: return InfoMsg;
        case 1: return GetGif;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EType>() {
            public EType findValueByNumber(int number) {
              return EType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rwproto.DailyGifProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final EType[] VALUES = values();

    public static EType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EType)
  }

  public interface DailyGifResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .EType type = 1;
    /**
     * <code>optional .EType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .EType type = 1;</code>
     */
    com.rwproto.DailyGifProtos.EType getType();

    // optional int32 count = 2;
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * ���ߴ���
     * </pre>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * ���ߴ���
     * </pre>
     */
    int getCount();

    // optional int32 getCount = 3;
    /**
     * <code>optional int32 getCount = 3;</code>
     *
     * <pre>
     * �������
     * </pre>
     */
    boolean hasGetCount();
    /**
     * <code>optional int32 getCount = 3;</code>
     *
     * <pre>
     * �������
     * </pre>
     */
    int getGetCount();
  }
  /**
   * Protobuf type {@code DailyGifResponse}
   */
  public static final class DailyGifResponse extends
      com.google.protobuf.GeneratedMessage
      implements DailyGifResponseOrBuilder {
    // Use DailyGifResponse.newBuilder() to construct.
    private DailyGifResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DailyGifResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DailyGifResponse defaultInstance;
    public static DailyGifResponse getDefaultInstance() {
      return defaultInstance;
    }

    public DailyGifResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DailyGifResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.DailyGifProtos.EType value = com.rwproto.DailyGifProtos.EType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              getCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.DailyGifProtos.internal_static_DailyGifResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.DailyGifProtos.internal_static_DailyGifResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.DailyGifProtos.DailyGifResponse.class, com.rwproto.DailyGifProtos.DailyGifResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<DailyGifResponse> PARSER =
        new com.google.protobuf.AbstractParser<DailyGifResponse>() {
      public DailyGifResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DailyGifResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DailyGifResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .EType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.rwproto.DailyGifProtos.EType type_;
    /**
     * <code>optional .EType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .EType type = 1;</code>
     */
    public com.rwproto.DailyGifProtos.EType getType() {
      return type_;
    }

    // optional int32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * ���ߴ���
     * </pre>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * ���ߴ���
     * </pre>
     */
    public int getCount() {
      return count_;
    }

    // optional int32 getCount = 3;
    public static final int GETCOUNT_FIELD_NUMBER = 3;
    private int getCount_;
    /**
     * <code>optional int32 getCount = 3;</code>
     *
     * <pre>
     * �������
     * </pre>
     */
    public boolean hasGetCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 getCount = 3;</code>
     *
     * <pre>
     * �������
     * </pre>
     */
    public int getGetCount() {
      return getCount_;
    }

    private void initFields() {
      type_ = com.rwproto.DailyGifProtos.EType.InfoMsg;
      count_ = 0;
      getCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, getCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.DailyGifProtos.DailyGifResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.DailyGifProtos.DailyGifResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.DailyGifProtos.DailyGifResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.DailyGifProtos.DailyGifResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.DailyGifProtos.DailyGifResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.DailyGifProtos.DailyGifResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.DailyGifProtos.DailyGifResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.DailyGifProtos.DailyGifResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.DailyGifProtos.DailyGifResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.DailyGifProtos.DailyGifResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.DailyGifProtos.DailyGifResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DailyGifResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.DailyGifProtos.DailyGifResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.DailyGifProtos.internal_static_DailyGifResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.DailyGifProtos.internal_static_DailyGifResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.DailyGifProtos.DailyGifResponse.class, com.rwproto.DailyGifProtos.DailyGifResponse.Builder.class);
      }

      // Construct using com.rwproto.DailyGifProtos.DailyGifResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.rwproto.DailyGifProtos.EType.InfoMsg;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        getCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.DailyGifProtos.internal_static_DailyGifResponse_descriptor;
      }

      public com.rwproto.DailyGifProtos.DailyGifResponse getDefaultInstanceForType() {
        return com.rwproto.DailyGifProtos.DailyGifResponse.getDefaultInstance();
      }

      public com.rwproto.DailyGifProtos.DailyGifResponse build() {
        com.rwproto.DailyGifProtos.DailyGifResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.DailyGifProtos.DailyGifResponse buildPartial() {
        com.rwproto.DailyGifProtos.DailyGifResponse result = new com.rwproto.DailyGifProtos.DailyGifResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.getCount_ = getCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.DailyGifProtos.DailyGifResponse) {
          return mergeFrom((com.rwproto.DailyGifProtos.DailyGifResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.DailyGifProtos.DailyGifResponse other) {
        if (other == com.rwproto.DailyGifProtos.DailyGifResponse.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasGetCount()) {
          setGetCount(other.getGetCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.DailyGifProtos.DailyGifResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.DailyGifProtos.DailyGifResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .EType type = 1;
      private com.rwproto.DailyGifProtos.EType type_ = com.rwproto.DailyGifProtos.EType.InfoMsg;
      /**
       * <code>optional .EType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .EType type = 1;</code>
       */
      public com.rwproto.DailyGifProtos.EType getType() {
        return type_;
      }
      /**
       * <code>optional .EType type = 1;</code>
       */
      public Builder setType(com.rwproto.DailyGifProtos.EType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .EType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.rwproto.DailyGifProtos.EType.InfoMsg;
        onChanged();
        return this;
      }

      // optional int32 count = 2;
      private int count_ ;
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * ���ߴ���
       * </pre>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * ���ߴ���
       * </pre>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * ���ߴ���
       * </pre>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * ���ߴ���
       * </pre>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      // optional int32 getCount = 3;
      private int getCount_ ;
      /**
       * <code>optional int32 getCount = 3;</code>
       *
       * <pre>
       * �������
       * </pre>
       */
      public boolean hasGetCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 getCount = 3;</code>
       *
       * <pre>
       * �������
       * </pre>
       */
      public int getGetCount() {
        return getCount_;
      }
      /**
       * <code>optional int32 getCount = 3;</code>
       *
       * <pre>
       * �������
       * </pre>
       */
      public Builder setGetCount(int value) {
        bitField0_ |= 0x00000004;
        getCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 getCount = 3;</code>
       *
       * <pre>
       * �������
       * </pre>
       */
      public Builder clearGetCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        getCount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DailyGifResponse)
    }

    static {
      defaultInstance = new DailyGifResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DailyGifResponse)
  }

  public interface DailyGifRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .EType type = 1;
    /**
     * <code>optional .EType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .EType type = 1;</code>
     */
    com.rwproto.DailyGifProtos.EType getType();

    // optional int32 count = 2;
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * ����
     * </pre>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * ����
     * </pre>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code DailyGifRequest}
   */
  public static final class DailyGifRequest extends
      com.google.protobuf.GeneratedMessage
      implements DailyGifRequestOrBuilder {
    // Use DailyGifRequest.newBuilder() to construct.
    private DailyGifRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DailyGifRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DailyGifRequest defaultInstance;
    public static DailyGifRequest getDefaultInstance() {
      return defaultInstance;
    }

    public DailyGifRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DailyGifRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.DailyGifProtos.EType value = com.rwproto.DailyGifProtos.EType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.DailyGifProtos.internal_static_DailyGifRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.DailyGifProtos.internal_static_DailyGifRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.DailyGifProtos.DailyGifRequest.class, com.rwproto.DailyGifProtos.DailyGifRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<DailyGifRequest> PARSER =
        new com.google.protobuf.AbstractParser<DailyGifRequest>() {
      public DailyGifRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DailyGifRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DailyGifRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .EType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.rwproto.DailyGifProtos.EType type_;
    /**
     * <code>optional .EType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .EType type = 1;</code>
     */
    public com.rwproto.DailyGifProtos.EType getType() {
      return type_;
    }

    // optional int32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * ����
     * </pre>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 count = 2;</code>
     *
     * <pre>
     * ����
     * </pre>
     */
    public int getCount() {
      return count_;
    }

    private void initFields() {
      type_ = com.rwproto.DailyGifProtos.EType.InfoMsg;
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.DailyGifProtos.DailyGifRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.DailyGifProtos.DailyGifRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.DailyGifProtos.DailyGifRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.DailyGifProtos.DailyGifRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.DailyGifProtos.DailyGifRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.DailyGifProtos.DailyGifRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.DailyGifProtos.DailyGifRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.DailyGifProtos.DailyGifRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.DailyGifProtos.DailyGifRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.DailyGifProtos.DailyGifRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.DailyGifProtos.DailyGifRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DailyGifRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.DailyGifProtos.DailyGifRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.DailyGifProtos.internal_static_DailyGifRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.DailyGifProtos.internal_static_DailyGifRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.DailyGifProtos.DailyGifRequest.class, com.rwproto.DailyGifProtos.DailyGifRequest.Builder.class);
      }

      // Construct using com.rwproto.DailyGifProtos.DailyGifRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.rwproto.DailyGifProtos.EType.InfoMsg;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.DailyGifProtos.internal_static_DailyGifRequest_descriptor;
      }

      public com.rwproto.DailyGifProtos.DailyGifRequest getDefaultInstanceForType() {
        return com.rwproto.DailyGifProtos.DailyGifRequest.getDefaultInstance();
      }

      public com.rwproto.DailyGifProtos.DailyGifRequest build() {
        com.rwproto.DailyGifProtos.DailyGifRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.DailyGifProtos.DailyGifRequest buildPartial() {
        com.rwproto.DailyGifProtos.DailyGifRequest result = new com.rwproto.DailyGifProtos.DailyGifRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.DailyGifProtos.DailyGifRequest) {
          return mergeFrom((com.rwproto.DailyGifProtos.DailyGifRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.DailyGifProtos.DailyGifRequest other) {
        if (other == com.rwproto.DailyGifProtos.DailyGifRequest.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.DailyGifProtos.DailyGifRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.DailyGifProtos.DailyGifRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .EType type = 1;
      private com.rwproto.DailyGifProtos.EType type_ = com.rwproto.DailyGifProtos.EType.InfoMsg;
      /**
       * <code>optional .EType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .EType type = 1;</code>
       */
      public com.rwproto.DailyGifProtos.EType getType() {
        return type_;
      }
      /**
       * <code>optional .EType type = 1;</code>
       */
      public Builder setType(com.rwproto.DailyGifProtos.EType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .EType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.rwproto.DailyGifProtos.EType.InfoMsg;
        onChanged();
        return this;
      }

      // optional int32 count = 2;
      private int count_ ;
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * ����
       * </pre>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * ����
       * </pre>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * ����
       * </pre>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 2;</code>
       *
       * <pre>
       * ����
       * </pre>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DailyGifRequest)
    }

    static {
      defaultInstance = new DailyGifRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DailyGifRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DailyGifResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DailyGifResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DailyGifRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DailyGifRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016DailyGif.proto\"I\n\020DailyGifResponse\022\024\n\004" +
      "type\030\001 \001(\0162\006.EType\022\r\n\005count\030\002 \001(\005\022\020\n\010get" +
      "Count\030\003 \001(\005\"6\n\017DailyGifRequest\022\024\n\004type\030\001" +
      " \001(\0162\006.EType\022\r\n\005count\030\002 \001(\005* \n\005EType\022\013\n\007" +
      "InfoMsg\020\000\022\n\n\006GetGif\020\001B\035\n\013com.rwprotoB\016Da" +
      "ilyGifProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DailyGifResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DailyGifResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DailyGifResponse_descriptor,
              new java.lang.String[] { "Type", "Count", "GetCount", });
          internal_static_DailyGifRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_DailyGifRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DailyGifRequest_descriptor,
              new java.lang.String[] { "Type", "Count", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
