// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupCopyAdminService.proto

package com.rwproto;

public final class GroupCopyAdminServiceProto {
  private GroupCopyAdminServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code groupproto.RequestType}
   *
   * <pre>
   *-----------------------【功能协议类型枚举】-----------------------
   * </pre>
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GET_COPY_INFO = 1;</code>
     *
     * <pre>
     *获取帮派副本信息
     * </pre>
     */
    GET_COPY_INFO(0, 1),
    /**
     * <code>COPY_OPEN = 2;</code>
     *
     * <pre>
     *开启帮派副本
     * </pre>
     */
    COPY_OPEN(1, 2),
    /**
     * <code>COPY_RESET = 3;</code>
     *
     * <pre>
     *重置帮派副本
     * </pre>
     */
    COPY_RESET(2, 3),
    ;

    /**
     * <code>GET_COPY_INFO = 1;</code>
     *
     * <pre>
     *获取帮派副本信息
     * </pre>
     */
    public static final int GET_COPY_INFO_VALUE = 1;
    /**
     * <code>COPY_OPEN = 2;</code>
     *
     * <pre>
     *开启帮派副本
     * </pre>
     */
    public static final int COPY_OPEN_VALUE = 2;
    /**
     * <code>COPY_RESET = 3;</code>
     *
     * <pre>
     *重置帮派副本
     * </pre>
     */
    public static final int COPY_RESET_VALUE = 3;


    public final int getNumber() { return value; }

    public static RequestType valueOf(int value) {
      switch (value) {
        case 1: return GET_COPY_INFO;
        case 2: return COPY_OPEN;
        case 3: return COPY_RESET;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rwproto.GroupCopyAdminServiceProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:groupproto.RequestType)
  }

  public interface GroupCooyAdminCommonReqMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .groupproto.RequestType reqType = 1;
    /**
     * <code>required .groupproto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求协议类型
     * </pre>
     */
    boolean hasReqType();
    /**
     * <code>required .groupproto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求协议类型
     * </pre>
     */
    com.rwproto.GroupCopyAdminServiceProto.RequestType getReqType();

    // optional string versionJson = 2;
    /**
     * <code>optional string versionJson = 2;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    boolean hasVersionJson();
    /**
     * <code>optional string versionJson = 2;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    java.lang.String getVersionJson();
    /**
     * <code>optional string versionJson = 2;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    com.google.protobuf.ByteString
        getVersionJsonBytes();
  }
  /**
   * Protobuf type {@code groupproto.GroupCooyAdminCommonReqMsg}
   */
  public static final class GroupCooyAdminCommonReqMsg extends
      com.google.protobuf.GeneratedMessage
      implements GroupCooyAdminCommonReqMsgOrBuilder {
    // Use GroupCooyAdminCommonReqMsg.newBuilder() to construct.
    private GroupCooyAdminCommonReqMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GroupCooyAdminCommonReqMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GroupCooyAdminCommonReqMsg defaultInstance;
    public static GroupCooyAdminCommonReqMsg getDefaultInstance() {
      return defaultInstance;
    }

    public GroupCooyAdminCommonReqMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GroupCooyAdminCommonReqMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.GroupCopyAdminServiceProto.RequestType value = com.rwproto.GroupCopyAdminServiceProto.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                reqType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              versionJson_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonReqMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonReqMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg.class, com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<GroupCooyAdminCommonReqMsg> PARSER =
        new com.google.protobuf.AbstractParser<GroupCooyAdminCommonReqMsg>() {
      public GroupCooyAdminCommonReqMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupCooyAdminCommonReqMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GroupCooyAdminCommonReqMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .groupproto.RequestType reqType = 1;
    public static final int REQTYPE_FIELD_NUMBER = 1;
    private com.rwproto.GroupCopyAdminServiceProto.RequestType reqType_;
    /**
     * <code>required .groupproto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求协议类型
     * </pre>
     */
    public boolean hasReqType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .groupproto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求协议类型
     * </pre>
     */
    public com.rwproto.GroupCopyAdminServiceProto.RequestType getReqType() {
      return reqType_;
    }

    // optional string versionJson = 2;
    public static final int VERSIONJSON_FIELD_NUMBER = 2;
    private java.lang.Object versionJson_;
    /**
     * <code>optional string versionJson = 2;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public boolean hasVersionJson() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string versionJson = 2;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public java.lang.String getVersionJson() {
      java.lang.Object ref = versionJson_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          versionJson_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string versionJson = 2;</code>
     *
     * <pre>
     *版本号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getVersionJsonBytes() {
      java.lang.Object ref = versionJson_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        versionJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      reqType_ = com.rwproto.GroupCopyAdminServiceProto.RequestType.GET_COPY_INFO;
      versionJson_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVersionJsonBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVersionJsonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code groupproto.GroupCooyAdminCommonReqMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonReqMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonReqMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg.class, com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg.Builder.class);
      }

      // Construct using com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqType_ = com.rwproto.GroupCopyAdminServiceProto.RequestType.GET_COPY_INFO;
        bitField0_ = (bitField0_ & ~0x00000001);
        versionJson_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonReqMsg_descriptor;
      }

      public com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg getDefaultInstanceForType() {
        return com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg.getDefaultInstance();
      }

      public com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg build() {
        com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg buildPartial() {
        com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg result = new com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqType_ = reqType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.versionJson_ = versionJson_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg) {
          return mergeFrom((com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg other) {
        if (other == com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg.getDefaultInstance()) return this;
        if (other.hasReqType()) {
          setReqType(other.getReqType());
        }
        if (other.hasVersionJson()) {
          bitField0_ |= 0x00000002;
          versionJson_ = other.versionJson_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonReqMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .groupproto.RequestType reqType = 1;
      private com.rwproto.GroupCopyAdminServiceProto.RequestType reqType_ = com.rwproto.GroupCopyAdminServiceProto.RequestType.GET_COPY_INFO;
      /**
       * <code>required .groupproto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求协议类型
       * </pre>
       */
      public boolean hasReqType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .groupproto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求协议类型
       * </pre>
       */
      public com.rwproto.GroupCopyAdminServiceProto.RequestType getReqType() {
        return reqType_;
      }
      /**
       * <code>required .groupproto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求协议类型
       * </pre>
       */
      public Builder setReqType(com.rwproto.GroupCopyAdminServiceProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .groupproto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求协议类型
       * </pre>
       */
      public Builder clearReqType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqType_ = com.rwproto.GroupCopyAdminServiceProto.RequestType.GET_COPY_INFO;
        onChanged();
        return this;
      }

      // optional string versionJson = 2;
      private java.lang.Object versionJson_ = "";
      /**
       * <code>optional string versionJson = 2;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public boolean hasVersionJson() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string versionJson = 2;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public java.lang.String getVersionJson() {
        java.lang.Object ref = versionJson_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          versionJson_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string versionJson = 2;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getVersionJsonBytes() {
        java.lang.Object ref = versionJson_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          versionJson_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string versionJson = 2;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder setVersionJson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        versionJson_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string versionJson = 2;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder clearVersionJson() {
        bitField0_ = (bitField0_ & ~0x00000002);
        versionJson_ = getDefaultInstance().getVersionJson();
        onChanged();
        return this;
      }
      /**
       * <code>optional string versionJson = 2;</code>
       *
       * <pre>
       *版本号
       * </pre>
       */
      public Builder setVersionJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        versionJson_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:groupproto.GroupCooyAdminCommonReqMsg)
    }

    static {
      defaultInstance = new GroupCooyAdminCommonReqMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:groupproto.GroupCooyAdminCommonReqMsg)
  }

  public interface GroupCooyAdminCommonRspMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .groupproto.RequestType reqType = 1;
    /**
     * <code>required .groupproto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求协议类型
     * </pre>
     */
    boolean hasReqType();
    /**
     * <code>required .groupproto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求协议类型
     * </pre>
     */
    com.rwproto.GroupCopyAdminServiceProto.RequestType getReqType();

    // required bool isSuccess = 2;
    /**
     * <code>required bool isSuccess = 2;</code>
     *
     * <pre>
     *是否成功处理
     * </pre>
     */
    boolean hasIsSuccess();
    /**
     * <code>required bool isSuccess = 2;</code>
     *
     * <pre>
     *是否成功处理
     * </pre>
     */
    boolean getIsSuccess();

    // optional string tipMsg = 3;
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    boolean hasTipMsg();
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    java.lang.String getTipMsg();
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    com.google.protobuf.ByteString
        getTipMsgBytes();
  }
  /**
   * Protobuf type {@code groupproto.GroupCooyAdminCommonRspMsg}
   */
  public static final class GroupCooyAdminCommonRspMsg extends
      com.google.protobuf.GeneratedMessage
      implements GroupCooyAdminCommonRspMsgOrBuilder {
    // Use GroupCooyAdminCommonRspMsg.newBuilder() to construct.
    private GroupCooyAdminCommonRspMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GroupCooyAdminCommonRspMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GroupCooyAdminCommonRspMsg defaultInstance;
    public static GroupCooyAdminCommonRspMsg getDefaultInstance() {
      return defaultInstance;
    }

    public GroupCooyAdminCommonRspMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GroupCooyAdminCommonRspMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.GroupCopyAdminServiceProto.RequestType value = com.rwproto.GroupCopyAdminServiceProto.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                reqType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isSuccess_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              tipMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonRspMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonRspMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg.class, com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<GroupCooyAdminCommonRspMsg> PARSER =
        new com.google.protobuf.AbstractParser<GroupCooyAdminCommonRspMsg>() {
      public GroupCooyAdminCommonRspMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupCooyAdminCommonRspMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GroupCooyAdminCommonRspMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .groupproto.RequestType reqType = 1;
    public static final int REQTYPE_FIELD_NUMBER = 1;
    private com.rwproto.GroupCopyAdminServiceProto.RequestType reqType_;
    /**
     * <code>required .groupproto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求协议类型
     * </pre>
     */
    public boolean hasReqType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .groupproto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求协议类型
     * </pre>
     */
    public com.rwproto.GroupCopyAdminServiceProto.RequestType getReqType() {
      return reqType_;
    }

    // required bool isSuccess = 2;
    public static final int ISSUCCESS_FIELD_NUMBER = 2;
    private boolean isSuccess_;
    /**
     * <code>required bool isSuccess = 2;</code>
     *
     * <pre>
     *是否成功处理
     * </pre>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool isSuccess = 2;</code>
     *
     * <pre>
     *是否成功处理
     * </pre>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    // optional string tipMsg = 3;
    public static final int TIPMSG_FIELD_NUMBER = 3;
    private java.lang.Object tipMsg_;
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    public boolean hasTipMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    public java.lang.String getTipMsg() {
      java.lang.Object ref = tipMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tipMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTipMsgBytes() {
      java.lang.Object ref = tipMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      reqType_ = com.rwproto.GroupCopyAdminServiceProto.RequestType.GET_COPY_INFO;
      isSuccess_ = false;
      tipMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isSuccess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTipMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isSuccess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTipMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code groupproto.GroupCooyAdminCommonRspMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonRspMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonRspMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg.class, com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg.Builder.class);
      }

      // Construct using com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqType_ = com.rwproto.GroupCopyAdminServiceProto.RequestType.GET_COPY_INFO;
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        tipMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.GroupCopyAdminServiceProto.internal_static_groupproto_GroupCooyAdminCommonRspMsg_descriptor;
      }

      public com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg getDefaultInstanceForType() {
        return com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg.getDefaultInstance();
      }

      public com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg build() {
        com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg buildPartial() {
        com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg result = new com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqType_ = reqType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tipMsg_ = tipMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg) {
          return mergeFrom((com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg other) {
        if (other == com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg.getDefaultInstance()) return this;
        if (other.hasReqType()) {
          setReqType(other.getReqType());
        }
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasTipMsg()) {
          bitField0_ |= 0x00000004;
          tipMsg_ = other.tipMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqType()) {
          
          return false;
        }
        if (!hasIsSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.GroupCopyAdminServiceProto.GroupCooyAdminCommonRspMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .groupproto.RequestType reqType = 1;
      private com.rwproto.GroupCopyAdminServiceProto.RequestType reqType_ = com.rwproto.GroupCopyAdminServiceProto.RequestType.GET_COPY_INFO;
      /**
       * <code>required .groupproto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求协议类型
       * </pre>
       */
      public boolean hasReqType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .groupproto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求协议类型
       * </pre>
       */
      public com.rwproto.GroupCopyAdminServiceProto.RequestType getReqType() {
        return reqType_;
      }
      /**
       * <code>required .groupproto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求协议类型
       * </pre>
       */
      public Builder setReqType(com.rwproto.GroupCopyAdminServiceProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .groupproto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求协议类型
       * </pre>
       */
      public Builder clearReqType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqType_ = com.rwproto.GroupCopyAdminServiceProto.RequestType.GET_COPY_INFO;
        onChanged();
        return this;
      }

      // required bool isSuccess = 2;
      private boolean isSuccess_ ;
      /**
       * <code>required bool isSuccess = 2;</code>
       *
       * <pre>
       *是否成功处理
       * </pre>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool isSuccess = 2;</code>
       *
       * <pre>
       *是否成功处理
       * </pre>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>required bool isSuccess = 2;</code>
       *
       * <pre>
       *是否成功处理
       * </pre>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000002;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSuccess = 2;</code>
       *
       * <pre>
       *是否成功处理
       * </pre>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      // optional string tipMsg = 3;
      private java.lang.Object tipMsg_ = "";
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public boolean hasTipMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public java.lang.String getTipMsg() {
        java.lang.Object ref = tipMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tipMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTipMsgBytes() {
        java.lang.Object ref = tipMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public Builder setTipMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tipMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public Builder clearTipMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tipMsg_ = getDefaultInstance().getTipMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public Builder setTipMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tipMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:groupproto.GroupCooyAdminCommonRspMsg)
    }

    static {
      defaultInstance = new GroupCooyAdminCommonRspMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:groupproto.GroupCooyAdminCommonRspMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_groupproto_GroupCooyAdminCommonReqMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_groupproto_GroupCooyAdminCommonReqMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_groupproto_GroupCooyAdminCommonRspMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_groupproto_GroupCooyAdminCommonRspMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033GroupCopyAdminService.proto\022\ngroupprot" +
      "o\"[\n\032GroupCooyAdminCommonReqMsg\022(\n\007reqTy" +
      "pe\030\001 \002(\0162\027.groupproto.RequestType\022\023\n\013ver" +
      "sionJson\030\002 \001(\t\"i\n\032GroupCooyAdminCommonRs" +
      "pMsg\022(\n\007reqType\030\001 \002(\0162\027.groupproto.Reque" +
      "stType\022\021\n\tisSuccess\030\002 \002(\010\022\016\n\006tipMsg\030\003 \001(" +
      "\t*?\n\013RequestType\022\021\n\rGET_COPY_INFO\020\001\022\r\n\tC" +
      "OPY_OPEN\020\002\022\016\n\nCOPY_RESET\020\003B)\n\013com.rwprot" +
      "oB\032GroupCopyAdminServiceProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_groupproto_GroupCooyAdminCommonReqMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_groupproto_GroupCooyAdminCommonReqMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_groupproto_GroupCooyAdminCommonReqMsg_descriptor,
              new java.lang.String[] { "ReqType", "VersionJson", });
          internal_static_groupproto_GroupCooyAdminCommonRspMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_groupproto_GroupCooyAdminCommonRspMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_groupproto_GroupCooyAdminCommonRspMsg_descriptor,
              new java.lang.String[] { "ReqType", "IsSuccess", "TipMsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
