// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgErrInfo.proto

package com.rwproto;

public final class MsgErrInfoProtos {
  private MsgErrInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code EMsgErrorInfoType}
   */
  public enum EMsgErrorInfoType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ServerMsg = 0;</code>
     *
     * <pre>
     *服务器错误
     * </pre>
     */
    ServerMsg(0, 0),
    /**
     * <code>ClientMsg = 1;</code>
     *
     * <pre>
     *客户端发送
     * </pre>
     */
    ClientMsg(1, 1),
    ;

    /**
     * <code>ServerMsg = 0;</code>
     *
     * <pre>
     *服务器错误
     * </pre>
     */
    public static final int ServerMsg_VALUE = 0;
    /**
     * <code>ClientMsg = 1;</code>
     *
     * <pre>
     *客户端发送
     * </pre>
     */
    public static final int ClientMsg_VALUE = 1;


    public final int getNumber() { return value; }

    public static EMsgErrorInfoType valueOf(int value) {
      switch (value) {
        case 0: return ServerMsg;
        case 1: return ClientMsg;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EMsgErrorInfoType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EMsgErrorInfoType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EMsgErrorInfoType>() {
            public EMsgErrorInfoType findValueByNumber(int number) {
              return EMsgErrorInfoType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rwproto.MsgErrInfoProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final EMsgErrorInfoType[] VALUES = values();

    public static EMsgErrorInfoType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EMsgErrorInfoType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EMsgErrorInfoType)
  }

  public interface MsgErrorInfoResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .EMsgErrorInfoType type = 1;
    /**
     * <code>optional .EMsgErrorInfoType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .EMsgErrorInfoType type = 1;</code>
     */
    com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType getType();

    // optional string msgInfo = 2;
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    boolean hasMsgInfo();
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    java.lang.String getMsgInfo();
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgInfoBytes();
  }
  /**
   * Protobuf type {@code MsgErrorInfoResponse}
   */
  public static final class MsgErrorInfoResponse extends
      com.google.protobuf.GeneratedMessage
      implements MsgErrorInfoResponseOrBuilder {
    // Use MsgErrorInfoResponse.newBuilder() to construct.
    private MsgErrorInfoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgErrorInfoResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgErrorInfoResponse defaultInstance;
    public static MsgErrorInfoResponse getDefaultInstance() {
      return defaultInstance;
    }

    public MsgErrorInfoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgErrorInfoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType value = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgInfo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse.class, com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgErrorInfoResponse> PARSER =
        new com.google.protobuf.AbstractParser<MsgErrorInfoResponse>() {
      public MsgErrorInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgErrorInfoResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgErrorInfoResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .EMsgErrorInfoType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType type_;
    /**
     * <code>optional .EMsgErrorInfoType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .EMsgErrorInfoType type = 1;</code>
     */
    public com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType getType() {
      return type_;
    }

    // optional string msgInfo = 2;
    public static final int MSGINFO_FIELD_NUMBER = 2;
    private java.lang.Object msgInfo_;
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    public boolean hasMsgInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    public java.lang.String getMsgInfo() {
      java.lang.Object ref = msgInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgInfoBytes() {
      java.lang.Object ref = msgInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.ServerMsg;
      msgInfo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgInfoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgInfoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MsgErrorInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse.class, com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse.Builder.class);
      }

      // Construct using com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.ServerMsg;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoResponse_descriptor;
      }

      public com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse getDefaultInstanceForType() {
        return com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse.getDefaultInstance();
      }

      public com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse build() {
        com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse buildPartial() {
        com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse result = new com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgInfo_ = msgInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse) {
          return mergeFrom((com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse other) {
        if (other == com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMsgInfo()) {
          bitField0_ |= 0x00000002;
          msgInfo_ = other.msgInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.MsgErrInfoProtos.MsgErrorInfoResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .EMsgErrorInfoType type = 1;
      private com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType type_ = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.ServerMsg;
      /**
       * <code>optional .EMsgErrorInfoType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .EMsgErrorInfoType type = 1;</code>
       */
      public com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType getType() {
        return type_;
      }
      /**
       * <code>optional .EMsgErrorInfoType type = 1;</code>
       */
      public Builder setType(com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .EMsgErrorInfoType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.ServerMsg;
        onChanged();
        return this;
      }

      // optional string msgInfo = 2;
      private java.lang.Object msgInfo_ = "";
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public boolean hasMsgInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public java.lang.String getMsgInfo() {
        java.lang.Object ref = msgInfo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgInfoBytes() {
        java.lang.Object ref = msgInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public Builder setMsgInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public Builder clearMsgInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgInfo_ = getDefaultInstance().getMsgInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public Builder setMsgInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgInfo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MsgErrorInfoResponse)
    }

    static {
      defaultInstance = new MsgErrorInfoResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MsgErrorInfoResponse)
  }

  public interface MsgErrorInfoRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .EMsgErrorInfoType type = 1;
    /**
     * <code>optional .EMsgErrorInfoType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .EMsgErrorInfoType type = 1;</code>
     */
    com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType getType();

    // optional string msgInfo = 2;
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    boolean hasMsgInfo();
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    java.lang.String getMsgInfo();
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgInfoBytes();
  }
  /**
   * Protobuf type {@code MsgErrorInfoRequest}
   */
  public static final class MsgErrorInfoRequest extends
      com.google.protobuf.GeneratedMessage
      implements MsgErrorInfoRequestOrBuilder {
    // Use MsgErrorInfoRequest.newBuilder() to construct.
    private MsgErrorInfoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgErrorInfoRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgErrorInfoRequest defaultInstance;
    public static MsgErrorInfoRequest getDefaultInstance() {
      return defaultInstance;
    }

    public MsgErrorInfoRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgErrorInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType value = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              msgInfo_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest.class, com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgErrorInfoRequest> PARSER =
        new com.google.protobuf.AbstractParser<MsgErrorInfoRequest>() {
      public MsgErrorInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgErrorInfoRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgErrorInfoRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .EMsgErrorInfoType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType type_;
    /**
     * <code>optional .EMsgErrorInfoType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .EMsgErrorInfoType type = 1;</code>
     */
    public com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType getType() {
      return type_;
    }

    // optional string msgInfo = 2;
    public static final int MSGINFO_FIELD_NUMBER = 2;
    private java.lang.Object msgInfo_;
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    public boolean hasMsgInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    public java.lang.String getMsgInfo() {
      java.lang.Object ref = msgInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msgInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgInfoBytes() {
      java.lang.Object ref = msgInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.ServerMsg;
      msgInfo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMsgInfoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMsgInfoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MsgErrorInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest.class, com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest.Builder.class);
      }

      // Construct using com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.ServerMsg;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.MsgErrInfoProtos.internal_static_MsgErrorInfoRequest_descriptor;
      }

      public com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest getDefaultInstanceForType() {
        return com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest.getDefaultInstance();
      }

      public com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest build() {
        com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest buildPartial() {
        com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest result = new com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msgInfo_ = msgInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest) {
          return mergeFrom((com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest other) {
        if (other == com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMsgInfo()) {
          bitField0_ |= 0x00000002;
          msgInfo_ = other.msgInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.MsgErrInfoProtos.MsgErrorInfoRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .EMsgErrorInfoType type = 1;
      private com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType type_ = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.ServerMsg;
      /**
       * <code>optional .EMsgErrorInfoType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .EMsgErrorInfoType type = 1;</code>
       */
      public com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType getType() {
        return type_;
      }
      /**
       * <code>optional .EMsgErrorInfoType type = 1;</code>
       */
      public Builder setType(com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .EMsgErrorInfoType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.rwproto.MsgErrInfoProtos.EMsgErrorInfoType.ServerMsg;
        onChanged();
        return this;
      }

      // optional string msgInfo = 2;
      private java.lang.Object msgInfo_ = "";
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public boolean hasMsgInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public java.lang.String getMsgInfo() {
        java.lang.Object ref = msgInfo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgInfoBytes() {
        java.lang.Object ref = msgInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public Builder setMsgInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public Builder clearMsgInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msgInfo_ = getDefaultInstance().getMsgInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msgInfo = 2;</code>
       */
      public Builder setMsgInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msgInfo_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MsgErrorInfoRequest)
    }

    static {
      defaultInstance = new MsgErrorInfoRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MsgErrorInfoRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MsgErrorInfoResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MsgErrorInfoResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MsgErrorInfoRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MsgErrorInfoRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MsgErrInfo.proto\"I\n\024MsgErrorInfoRespon" +
      "se\022 \n\004type\030\001 \001(\0162\022.EMsgErrorInfoType\022\017\n\007" +
      "msgInfo\030\002 \001(\t\"H\n\023MsgErrorInfoRequest\022 \n\004" +
      "type\030\001 \001(\0162\022.EMsgErrorInfoType\022\017\n\007msgInf" +
      "o\030\002 \001(\t*1\n\021EMsgErrorInfoType\022\r\n\tServerMs" +
      "g\020\000\022\r\n\tClientMsg\020\001B\037\n\013com.rwprotoB\020MsgEr" +
      "rInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MsgErrorInfoResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MsgErrorInfoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MsgErrorInfoResponse_descriptor,
              new java.lang.String[] { "Type", "MsgInfo", });
          internal_static_MsgErrorInfoRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MsgErrorInfoRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MsgErrorInfoRequest_descriptor,
              new java.lang.String[] { "Type", "MsgInfo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
