package ProtobufExp.Absyn; // Java Package generated by the BNF Converter.

public abstract class FieldModifier implements java.io.Serializable {
  public abstract <R,A> R accept(FieldModifier.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(ProtobufExp.Absyn.FieldModifier_required p, A arg);
    public R visit(ProtobufExp.Absyn.FieldModifier_optional p, A arg);
    public R visit(ProtobufExp.Absyn.FieldModifier_repeated p, A arg);

  }

}
