package com.rw.handler.sign;

public class EBtnStatus {
	public final static int CURRENT = 1;		//可正常签到...
	public final static int DOUBLE_ABLE = 2;	//剩余双倍...
	public final static int RESIGNABLE = 3;		//可补签...
	public final static int NOT_SIGN = 4;		//未签到...
	public final static int SIGN_YET = 5;		//已签到...
}
