//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ChatService.proto
namespace ChatService
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageUserInfo")]
  public partial class MessageUserInfo : global::ProtoBuf.IExtensible
  {
    public MessageUserInfo() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName?? ""; }
      set { _userName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool userNameSpecified
    {
      get { return this._userName != null; }
      set { if (value == (this._userName== null)) this._userName = value ? this.userName : (string)null; }
    }
    private bool ShouldSerializeuserName() { return userNameSpecified; }
    private void ResetuserName() { userNameSpecified = false; }
    
    private string _headImage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headImage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string headImage
    {
      get { return _headImage?? ""; }
      set { _headImage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool headImageSpecified
    {
      get { return this._headImage != null; }
      set { if (value == (this._headImage== null)) this._headImage = value ? this.headImage : (string)null; }
    }
    private bool ShouldSerializeheadImage() { return headImageSpecified; }
    private void ResetheadImage() { headImageSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private string _familyId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"familyId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string familyId
    {
      get { return _familyId?? ""; }
      set { _familyId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool familyIdSpecified
    {
      get { return this._familyId != null; }
      set { if (value == (this._familyId== null)) this._familyId = value ? this.familyId : (string)null; }
    }
    private bool ShouldSerializefamilyId() { return familyIdSpecified; }
    private void ResetfamilyId() { familyIdSpecified = false; }
    
    private string _familyName;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"familyName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string familyName
    {
      get { return _familyName?? ""; }
      set { _familyName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool familyNameSpecified
    {
      get { return this._familyName != null; }
      set { if (value == (this._familyName== null)) this._familyName = value ? this.familyName : (string)null; }
    }
    private bool ShouldSerializefamilyName() { return familyNameSpecified; }
    private void ResetfamilyName() { familyNameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatMessageData")]
  public partial class ChatMessageData : global::ProtoBuf.IExtensible
  {
    public ChatMessageData() {}
    
    private MessageUserInfo _sendMessageUserInfo;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sendMessageUserInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MessageUserInfo sendMessageUserInfo
    {
      get { return _sendMessageUserInfo; }
      set { _sendMessageUserInfo = value; }
    }
    private MessageUserInfo _receiveMessageUserInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"receiveMessageUserInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MessageUserInfo receiveMessageUserInfo
    {
      get { return _receiveMessageUserInfo; }
      set { _receiveMessageUserInfo = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private string _time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string time
    {
      get { return _time?? ""; }
      set { _time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timeSpecified
    {
      get { return this._time != null; }
      set { if (value == (this._time== null)) this._time = value ? this.time : (string)null; }
    }
    private bool ShouldSerializetime() { return timeSpecified; }
    private void Resettime() { timeSpecified = false; }
    
    private string _treasureName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"treasureName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string treasureName
    {
      get { return _treasureName?? ""; }
      set { _treasureName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool treasureNameSpecified
    {
      get { return this._treasureName != null; }
      set { if (value == (this._treasureName== null)) this._treasureName = value ? this.treasureName : (string)null; }
    }
    private bool ShouldSerializetreasureName() { return treasureNameSpecified; }
    private void ResettreasureName() { treasureNameSpecified = false; }
    
    private int? _treasureDefNum;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"treasureDefNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int treasureDefNum
    {
      get { return _treasureDefNum?? default(int); }
      set { _treasureDefNum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool treasureDefNumSpecified
    {
      get { return this._treasureDefNum != null; }
      set { if (value == (this._treasureDefNum== null)) this._treasureDefNum = value ? this.treasureDefNum : (int?)null; }
    }
    private bool ShouldSerializetreasureDefNum() { return treasureDefNumSpecified; }
    private void ResettreasureDefNum() { treasureDefNumSpecified = false; }
    
    private string _treasureId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"treasureId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string treasureId
    {
      get { return _treasureId?? ""; }
      set { _treasureId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool treasureIdSpecified
    {
      get { return this._treasureId != null; }
      set { if (value == (this._treasureId== null)) this._treasureId = value ? this.treasureId : (string)null; }
    }
    private bool ShouldSerializetreasureId() { return treasureIdSpecified; }
    private void ResettreasureId() { treasureIdSpecified = false; }
    
    private int? _treasureType;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"treasureType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int treasureType
    {
      get { return _treasureType?? default(int); }
      set { _treasureType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool treasureTypeSpecified
    {
      get { return this._treasureType != null; }
      set { if (value == (this._treasureType== null)) this._treasureType = value ? this.treasureType : (int?)null; }
    }
    private bool ShouldSerializetreasureType() { return treasureTypeSpecified; }
    private void ResettreasureType() { treasureTypeSpecified = false; }
    
    private bool? _isRead;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isRead", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isRead
    {
      get { return _isRead?? default(bool); }
      set { _isRead = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool isReadSpecified
    {
      get { return this._isRead != null; }
      set { if (value == (this._isRead== null)) this._isRead = value ? this.isRead : (bool?)null; }
    }
    private bool ShouldSerializeisRead() { return isReadSpecified; }
    private void ResetisRead() { isReadSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgChatRequest")]
  public partial class MsgChatRequest : global::ProtoBuf.IExtensible
  {
    public MsgChatRequest() {}
    
    private eChatType _ChatType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ChatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public eChatType ChatType
    {
      get { return _ChatType; }
      set { _ChatType = value; }
    }
    private ChatMessageData _chatMessageData = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"chatMessageData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ChatMessageData chatMessageData
    {
      get { return _chatMessageData; }
      set { _chatMessageData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgChatResponse")]
  public partial class MsgChatResponse : global::ProtoBuf.IExtensible
  {
    public MsgChatResponse() {}
    
    private eChatType _chatType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chatType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public eChatType chatType
    {
      get { return _chatType; }
      set { _chatType = value; }
    }
    private eChatResultType? _chatResultType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"chatResultType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public eChatResultType chatResultType
    {
      get { return _chatResultType?? eChatResultType.SUCCESS; }
      set { _chatResultType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool chatResultTypeSpecified
    {
      get { return this._chatResultType != null; }
      set { if (value == (this._chatResultType== null)) this._chatResultType = value ? this.chatResultType : (eChatResultType?)null; }
    }
    private bool ShouldSerializechatResultType() { return chatResultTypeSpecified; }
    private void ResetchatResultType() { chatResultTypeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<ChatMessageData> _listMessage = new global::System.Collections.Generic.List<ChatMessageData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"listMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ChatMessageData> listMessage
    {
      get { return _listMessage; }
    }
  
    private bool? _onLogin;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"onLogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool onLogin
    {
      get { return _onLogin?? default(bool); }
      set { _onLogin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool onLoginSpecified
    {
      get { return this._onLogin != null; }
      set { if (value == (this._onLogin== null)) this._onLogin = value ? this.onLogin : (bool?)null; }
    }
    private bool ShouldSerializeonLogin() { return onLoginSpecified; }
    private void ResetonLogin() { onLoginSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"eChatType")]
    public enum eChatType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_WORLD", Value=1)]
      CHAT_WORLD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_FAMILY", Value=2)]
      CHAT_FAMILY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_PERSON", Value=3)]
      CHAT_PERSON = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHAT_TREASURE", Value=4)]
      CHAT_TREASURE = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eChatResultType")]
    public enum eChatResultType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=1)]
      SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=2)]
      FAIL = 2
    }
  
}