//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ClientView.proto
// Note: requires additional types generated from: GuidanceService.proto
// Note: requires additional types generated from: PlotView.proto
namespace ClientView
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientViewData")]
  public partial class ClientViewData : global::ProtoBuf.IExtensible
  {
    public ClientViewData() {}
    
    private readonly global::System.Collections.Generic.List<GuidanceService.GuidanceProgress> _guideProg = new global::System.Collections.Generic.List<GuidanceService.GuidanceProgress>();
    [global::ProtoBuf.ProtoMember(1, Name=@"guideProg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<GuidanceService.GuidanceProgress> guideProg
    {
      get { return _guideProg; }
    }
  
    private readonly global::System.Collections.Generic.List<PlotView.PlotProgress> _plotProg = new global::System.Collections.Generic.List<PlotView.PlotProgress>();
    [global::ProtoBuf.ProtoMember(2, Name=@"plotProg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PlotView.PlotProgress> plotProg
    {
      get { return _plotProg; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}