//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: CopyService.proto
namespace CopyService
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgCopyRequest")]
  public partial class MsgCopyRequest : global::ProtoBuf.IExtensible
  {
    public MsgCopyRequest() {}
    
    private ERequestType _requestType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"requestType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ERequestType requestType
    {
      get { return _requestType; }
      set { _requestType = value; }
    }
    private int? _levelId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelId
    {
      get { return _levelId?? default(int); }
      set { _levelId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelIdSpecified
    {
      get { return this._levelId != null; }
      set { if (value == (this._levelId== null)) this._levelId = value ? this.levelId : (int?)null; }
    }
    private bool ShouldSerializelevelId() { return levelIdSpecified; }
    private void ResetlevelId() { levelIdSpecified = false; }
    
    private TagBattleData _tagBattleData = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tagBattleData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TagBattleData tagBattleData
    {
      get { return _tagBattleData; }
      set { _tagBattleData = value; }
    }
    private MapGiftRequest _mapGiftRequest = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mapGiftRequest", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MapGiftRequest mapGiftRequest
    {
      get { return _mapGiftRequest; }
      set { _mapGiftRequest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgCopyResponse")]
  public partial class MsgCopyResponse : global::ProtoBuf.IExtensible
  {
    public MsgCopyResponse() {}
    
    private EResultType? _eResultType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eResultType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EResultType eResultType
    {
      get { return _eResultType?? EResultType.NONE; }
      set { _eResultType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool eResultTypeSpecified
    {
      get { return this._eResultType != null; }
      set { if (value == (this._eResultType== null)) this._eResultType = value ? this.eResultType : (EResultType?)null; }
    }
    private bool ShouldSerializeeResultType() { return eResultTypeSpecified; }
    private void ReseteResultType() { eResultTypeSpecified = false; }
    
    private ERequestType? _requestType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"requestType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ERequestType requestType
    {
      get { return _requestType?? ERequestType.SWEEP_LEVEL_TICKET; }
      set { _requestType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool requestTypeSpecified
    {
      get { return this._requestType != null; }
      set { if (value == (this._requestType== null)) this._requestType = value ? this.requestType : (ERequestType?)null; }
    }
    private bool ShouldSerializerequestType() { return requestTypeSpecified; }
    private void ResetrequestType() { requestTypeSpecified = false; }
    
    private TagBattleClearingResult _tagBattleClearingResult = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tagBattleClearingResult", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public TagBattleClearingResult tagBattleClearingResult
    {
      get { return _tagBattleClearingResult; }
      set { _tagBattleClearingResult = value; }
    }
    private int? _levelId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelId
    {
      get { return _levelId?? default(int); }
      set { _levelId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelIdSpecified
    {
      get { return this._levelId != null; }
      set { if (value == (this._levelId== null)) this._levelId = value ? this.levelId : (int?)null; }
    }
    private bool ShouldSerializelevelId() { return levelIdSpecified; }
    private void ResetlevelId() { levelIdSpecified = false; }
    
    private int? _clearCount;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"clearCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int clearCount
    {
      get { return _clearCount?? default(int); }
      set { _clearCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool clearCountSpecified
    {
      get { return this._clearCount != null; }
      set { if (value == (this._clearCount== null)) this._clearCount = value ? this.clearCount : (int?)null; }
    }
    private bool ShouldSerializeclearCount() { return clearCountSpecified; }
    private void ResetclearCount() { clearCountSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<TagSweepInfo> _tagSweepInfoList = new global::System.Collections.Generic.List<TagSweepInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"tagSweepInfoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TagSweepInfo> tagSweepInfoList
    {
      get { return _tagSweepInfoList; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _tagMapRecord = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(7, Name=@"tagMapRecord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> tagMapRecord
    {
      get { return _tagMapRecord; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _tagCopyLevelRecord = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(8, Name=@"tagCopyLevelRecord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> tagCopyLevelRecord
    {
      get { return _tagCopyLevelRecord; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _tagItemList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(9, Name=@"tagItemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> tagItemList
    {
      get { return _tagItemList; }
    }
  
    private int? _copyCount;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"copyCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int copyCount
    {
      get { return _copyCount?? default(int); }
      set { _copyCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool copyCountSpecified
    {
      get { return this._copyCount != null; }
      set { if (value == (this._copyCount== null)) this._copyCount = value ? this.copyCount : (int?)null; }
    }
    private bool ShouldSerializecopyCount() { return copyCountSpecified; }
    private void ResetcopyCount() { copyCountSpecified = false; }
    
    private int? _unendingWar;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"unendingWar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int unendingWar
    {
      get { return _unendingWar?? default(int); }
      set { _unendingWar = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool unendingWarSpecified
    {
      get { return this._unendingWar != null; }
      set { if (value == (this._unendingWar== null)) this._unendingWar = value ? this.unendingWar : (int?)null; }
    }
    private bool ShouldSerializeunendingWar() { return unendingWarSpecified; }
    private void ResetunendingWar() { unendingWarSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TagSweepInfo")]
  public partial class TagSweepInfo : global::ProtoBuf.IExtensible
  {
    public TagSweepInfo() {}
    
    private int _times;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _tagItemList = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tagItemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> tagItemList
    {
      get { return _tagItemList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapGiftRequest")]
  public partial class MapGiftRequest : global::ProtoBuf.IExtensible
  {
    public MapGiftRequest() {}
    
    private int _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mapId
    {
      get { return _mapId; }
      set { _mapId = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TagBattleData")]
  public partial class TagBattleData : global::ProtoBuf.IExtensible
  {
    public TagBattleData() {}
    
    private int _battleClearingTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"battleClearingTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int battleClearingTime
    {
      get { return _battleClearingTime; }
      set { _battleClearingTime = value; }
    }
    private int _levelId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"levelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int levelId
    {
      get { return _levelId; }
      set { _levelId = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _heroId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> heroId
    {
      get { return _heroId; }
    }
  
    private int? _starLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"starLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int starLevel
    {
      get { return _starLevel?? default(int); }
      set { _starLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool starLevelSpecified
    {
      get { return this._starLevel != null; }
      set { if (value == (this._starLevel== null)) this._starLevel = value ? this.starLevel : (int?)null; }
    }
    private bool ShouldSerializestarLevel() { return starLevelSpecified; }
    private void ResetstarLevel() { starLevelSpecified = false; }
    
    private EBattleStatus? _battleStatus;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"battleStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EBattleStatus battleStatus
    {
      get { return _battleStatus?? EBattleStatus.WIN; }
      set { _battleStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool battleStatusSpecified
    {
      get { return this._battleStatus != null; }
      set { if (value == (this._battleStatus== null)) this._battleStatus = value ? this.battleStatus : (EBattleStatus?)null; }
    }
    private bool ShouldSerializebattleStatus() { return battleStatusSpecified; }
    private void ResetbattleStatus() { battleStatusSpecified = false; }
    
    private int? _fightTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fightTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fightTime
    {
      get { return _fightTime?? default(int); }
      set { _fightTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fightTimeSpecified
    {
      get { return this._fightTime != null; }
      set { if (value == (this._fightTime== null)) this._fightTime = value ? this.fightTime : (int?)null; }
    }
    private bool ShouldSerializefightTime() { return fightTimeSpecified; }
    private void ResetfightTime() { fightTimeSpecified = false; }
    
    private EBattleStatus? _fightResult;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fightResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EBattleStatus fightResult
    {
      get { return _fightResult?? EBattleStatus.WIN; }
      set { _fightResult = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fightResultSpecified
    {
      get { return this._fightResult != null; }
      set { if (value == (this._fightResult== null)) this._fightResult = value ? this.fightResult : (EBattleStatus?)null; }
    }
    private bool ShouldSerializefightResult() { return fightResultSpecified; }
    private void ResetfightResult() { fightResultSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TagBattleClearingResult")]
  public partial class TagBattleClearingResult : global::ProtoBuf.IExtensible
  {
    public TagBattleClearingResult() {}
    
    private readonly global::System.Collections.Generic.List<string> _upHeroId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"upHeroId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> upHeroId
    {
      get { return _upHeroId; }
    }
  
    private string _tagCopyRecord;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tagCopyRecord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tagCopyRecord
    {
      get { return _tagCopyRecord?? ""; }
      set { _tagCopyRecord = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tagCopyRecordSpecified
    {
      get { return this._tagCopyRecord != null; }
      set { if (value == (this._tagCopyRecord== null)) this._tagCopyRecord = value ? this.tagCopyRecord : (string)null; }
    }
    private bool ShouldSerializetagCopyRecord() { return tagCopyRecordSpecified; }
    private void ResettagCopyRecord() { tagCopyRecordSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ERequestType")]
    public enum ERequestType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SWEEP_LEVEL_TICKET", Value=1)]
      SWEEP_LEVEL_TICKET = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SWEEP_LEVEL_DIAMOND", Value=2)]
      SWEEP_LEVEL_DIAMOND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUY_LEVEL", Value=3)]
      BUY_LEVEL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_USER_CHECKPOINT_INFO", Value=4)]
      GET_USER_CHECKPOINT_INFO = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_CLEARING", Value=5)]
      BATTLE_CLEARING = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_ITEMS_BACK", Value=6)]
      BATTLE_ITEMS_BACK = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GM_SETLEVEL", Value=7)]
      GM_SETLEVEL = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_GIFT", Value=8)]
      GET_GIFT = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EBattleStatus")]
    public enum EBattleStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WIN", Value=1)]
      WIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TIMES_UP", Value=2)]
      TIMES_UP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NULL", Value=3)]
      NULL = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EResultType")]
    public enum EResultType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=1)]
      NONE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PURCHASE_SUCCESS", Value=2)]
      PURCHASE_SUCCESS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOW_VIP", Value=3)]
      LOW_VIP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_DIAMOND", Value=4)]
      NOT_ENOUGH_DIAMOND = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_HP", Value=5)]
      NOT_ENOUGH_HP = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_OPEN", Value=6)]
      NOT_OPEN = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_TICKET", Value=7)]
      NOT_ENOUGH_TICKET = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_ENOUGH_TIMES", Value=8)]
      NOT_ENOUGH_TIMES = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INIT_MAP", Value=9)]
      INIT_MAP = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ITEM_BACK", Value=10)]
      ITEM_BACK = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BATTLE_CLEAR", Value=11)]
      BATTLE_CLEAR = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GM_SETSUCCESS", Value=12)]
      GM_SETSUCCESS = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SWEEP_SUCCESS", Value=13)]
      SWEEP_SUCCESS = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GET_GIFT_SUCCESS", Value=14)]
      GET_GIFT_SUCCESS = 14
    }
  
}