//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GroupBaseMgr.proto
// Note: requires additional types generated from: GroupCommon.proto
namespace groupproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateGroupReqMsg")]
  public partial class CreateGroupReqMsg : global::ProtoBuf.IExtensible
  {
    public CreateGroupReqMsg() {}
    
    private string _groupName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string groupName
    {
      get { return _groupName; }
      set { _groupName = value; }
    }
    private string _icon;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateGroupRspMsg")]
  public partial class CreateGroupRspMsg : global::ProtoBuf.IExtensible
  {
    public CreateGroupRspMsg() {}
    
    private int? _rankIndex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rankIndex
    {
      get { return _rankIndex?? default(int); }
      set { _rankIndex = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankIndexSpecified
    {
      get { return this._rankIndex != null; }
      set { if (value == (this._rankIndex== null)) this._rankIndex = value ? this.rankIndex : (int?)null; }
    }
    private bool ShouldSerializerankIndex() { return rankIndexSpecified; }
    private void ResetrankIndex() { rankIndexSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModifyGroupNameReqMsg")]
  public partial class ModifyGroupNameReqMsg : global::ProtoBuf.IExtensible
  {
    public ModifyGroupNameReqMsg() {}
    
    private string _groupName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string groupName
    {
      get { return _groupName; }
      set { _groupName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModifyAnnouncementReqMsg")]
  public partial class ModifyAnnouncementReqMsg : global::ProtoBuf.IExtensible
  {
    public ModifyAnnouncementReqMsg() {}
    
    private string _announcement;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"announcement", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string announcement
    {
      get { return _announcement; }
      set { _announcement = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupSettingReqMsg")]
  public partial class GroupSettingReqMsg : global::ProtoBuf.IExtensible
  {
    public GroupSettingReqMsg() {}
    
    private string _groupIcon;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"groupIcon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string groupIcon
    {
      get { return _groupIcon?? ""; }
      set { _groupIcon = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool groupIconSpecified
    {
      get { return this._groupIcon != null; }
      set { if (value == (this._groupIcon== null)) this._groupIcon = value ? this.groupIcon : (string)null; }
    }
    private bool ShouldSerializegroupIcon() { return groupIconSpecified; }
    private void ResetgroupIcon() { groupIconSpecified = false; }
    
    private string _declaration;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"declaration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string declaration
    {
      get { return _declaration?? ""; }
      set { _declaration = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool declarationSpecified
    {
      get { return this._declaration != null; }
      set { if (value == (this._declaration== null)) this._declaration = value ? this.declaration : (string)null; }
    }
    private bool ShouldSerializedeclaration() { return declarationSpecified; }
    private void Resetdeclaration() { declarationSpecified = false; }
    
    private groupproto.GroupValidateType? _validateType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"validateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public groupproto.GroupValidateType validateType
    {
      get { return _validateType?? groupproto.GroupValidateType.NON; }
      set { _validateType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool validateTypeSpecified
    {
      get { return this._validateType != null; }
      set { if (value == (this._validateType== null)) this._validateType = value ? this.validateType : (groupproto.GroupValidateType?)null; }
    }
    private bool ShouldSerializevalidateType() { return validateTypeSpecified; }
    private void ResetvalidateType() { validateTypeSpecified = false; }
    
    private int? _applyLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"applyLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int applyLevel
    {
      get { return _applyLevel?? default(int); }
      set { _applyLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool applyLevelSpecified
    {
      get { return this._applyLevel != null; }
      set { if (value == (this._applyLevel== null)) this._applyLevel = value ? this.applyLevel : (int?)null; }
    }
    private bool ShouldSerializeapplyLevel() { return applyLevelSpecified; }
    private void ResetapplyLevel() { applyLevelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupBaseMgrCommonReqMsg")]
  public partial class GroupBaseMgrCommonReqMsg : global::ProtoBuf.IExtensible
  {
    public GroupBaseMgrCommonReqMsg() {}
    
    private groupproto.RequestType _reqType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"reqType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public groupproto.RequestType reqType
    {
      get { return _reqType; }
      set { _reqType = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version?? ""; }
      set { _version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool versionSpecified
    {
      get { return this._version != null; }
      set { if (value == (this._version== null)) this._version = value ? this.version : (string)null; }
    }
    private bool ShouldSerializeversion() { return versionSpecified; }
    private void Resetversion() { versionSpecified = false; }
    
    private groupproto.CreateGroupReqMsg _createGroupReq = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"createGroupReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public groupproto.CreateGroupReqMsg createGroupReq
    {
      get { return _createGroupReq; }
      set { _createGroupReq = value; }
    }
    private groupproto.ModifyGroupNameReqMsg _modifyGroupNameReq = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"modifyGroupNameReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public groupproto.ModifyGroupNameReqMsg modifyGroupNameReq
    {
      get { return _modifyGroupNameReq; }
      set { _modifyGroupNameReq = value; }
    }
    private groupproto.ModifyAnnouncementReqMsg _modifyAnnouncementReq = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"modifyAnnouncementReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public groupproto.ModifyAnnouncementReqMsg modifyAnnouncementReq
    {
      get { return _modifyAnnouncementReq; }
      set { _modifyAnnouncementReq = value; }
    }
    private groupproto.GroupSettingReqMsg _groupSettingReq = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"groupSettingReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public groupproto.GroupSettingReqMsg groupSettingReq
    {
      get { return _groupSettingReq; }
      set { _groupSettingReq = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GroupBaseMgrCommonRspMsg")]
  public partial class GroupBaseMgrCommonRspMsg : global::ProtoBuf.IExtensible
  {
    public GroupBaseMgrCommonRspMsg() {}
    
    private groupproto.RequestType _reqType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"reqType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public groupproto.RequestType reqType
    {
      get { return _reqType; }
      set { _reqType = value; }
    }
    private bool _isSuccess;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isSuccess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isSuccess
    {
      get { return _isSuccess; }
      set { _isSuccess = value; }
    }
    private string _tipMsg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tipMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tipMsg
    {
      get { return _tipMsg?? ""; }
      set { _tipMsg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tipMsgSpecified
    {
      get { return this._tipMsg != null; }
      set { if (value == (this._tipMsg== null)) this._tipMsg = value ? this.tipMsg : (string)null; }
    }
    private bool ShouldSerializetipMsg() { return tipMsgSpecified; }
    private void ResettipMsg() { tipMsgSpecified = false; }
    
    private groupproto.CreateGroupRspMsg _createGroupRsp = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"createGroupRsp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public groupproto.CreateGroupRspMsg createGroupRsp
    {
      get { return _createGroupRsp; }
      set { _createGroupRsp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}