//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: response.proto
// Note: requires additional types generated from: MsgDef.proto
namespace response
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Response")]
  public partial class Response : global::ProtoBuf.IExtensible
  {
    public Response() {}
    
    private ResponseHeader _header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ResponseHeader header
    {
      get { return _header; }
      set { _header = value; }
    }
    private byte[] _serialized_content;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serialized_content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] serialized_content
    {
      get { return _serialized_content?? null; }
      set { _serialized_content = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool serialized_contentSpecified
    {
      get { return this._serialized_content != null; }
      set { if (value == (this._serialized_content== null)) this._serialized_content = value ? this.serialized_content : (byte[])null; }
    }
    private bool ShouldSerializeserialized_content() { return serialized_contentSpecified; }
    private void Resetserialized_content() { serialized_contentSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseHeader")]
  public partial class ResponseHeader : global::ProtoBuf.IExtensible
  {
    public ResponseHeader() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private MsgDef.Command _command;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public MsgDef.Command command
    {
      get { return _command; }
      set { _command = value; }
    }
    private int _StatusCode;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"StatusCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int StatusCode
    {
      get { return _StatusCode; }
      set { _StatusCode = value; }
    }
    private int? _seqID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"seqID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seqID
    {
      get { return _seqID?? default(int); }
      set { _seqID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool seqIDSpecified
    {
      get { return this._seqID != null; }
      set { if (value == (this._seqID== null)) this._seqID = value ? this.seqID : (int?)null; }
    }
    private bool ShouldSerializeseqID() { return seqIDSpecified; }
    private void ResetseqID() { seqIDSpecified = false; }
    
    private string _ErrorMsg;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ErrorMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ErrorMsg
    {
      get { return _ErrorMsg?? ""; }
      set { _ErrorMsg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ErrorMsgSpecified
    {
      get { return this._ErrorMsg != null; }
      set { if (value == (this._ErrorMsg== null)) this._ErrorMsg = value ? this.ErrorMsg : (string)null; }
    }
    private bool ShouldSerializeErrorMsg() { return ErrorMsgSpecified; }
    private void ResetErrorMsg() { ErrorMsgSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}