// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleVerify.proto

package com.rwproto;

public final class BattleVerifyProto {
  private BattleVerifyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code BattleVerifyProto.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Copy = 1;</code>
     */
    Copy(0, 1),
    ;

    /**
     * <code>Copy = 1;</code>
     */
    public static final int Copy_VALUE = 1;


    public final int getNumber() { return value; }

    public static RequestType valueOf(int value) {
      switch (value) {
        case 1: return Copy;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rwproto.BattleVerifyProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BattleVerifyProto.RequestType)
  }

  public interface CopyReqMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string copyId = 1;
    /**
     * <code>required string copyId = 1;</code>
     *
     * <pre>
     *副本id
     * </pre>
     */
    boolean hasCopyId();
    /**
     * <code>required string copyId = 1;</code>
     *
     * <pre>
     *副本id
     * </pre>
     */
    java.lang.String getCopyId();
    /**
     * <code>required string copyId = 1;</code>
     *
     * <pre>
     *副本id
     * </pre>
     */
    com.google.protobuf.ByteString
        getCopyIdBytes();

    // required string code = 2;
    /**
     * <code>required string code = 2;</code>
     *
     * <pre>
     *校验密码
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>required string code = 2;</code>
     *
     * <pre>
     *校验密码
     * </pre>
     */
    java.lang.String getCode();
    /**
     * <code>required string code = 2;</code>
     *
     * <pre>
     *校验密码
     * </pre>
     */
    com.google.protobuf.ByteString
        getCodeBytes();
  }
  /**
   * Protobuf type {@code BattleVerifyProto.CopyReqMsg}
   */
  public static final class CopyReqMsg extends
      com.google.protobuf.GeneratedMessage
      implements CopyReqMsgOrBuilder {
    // Use CopyReqMsg.newBuilder() to construct.
    private CopyReqMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CopyReqMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CopyReqMsg defaultInstance;
    public static CopyReqMsg getDefaultInstance() {
      return defaultInstance;
    }

    public CopyReqMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CopyReqMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              copyId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              code_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_CopyReqMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_CopyReqMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.BattleVerifyProto.CopyReqMsg.class, com.rwproto.BattleVerifyProto.CopyReqMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<CopyReqMsg> PARSER =
        new com.google.protobuf.AbstractParser<CopyReqMsg>() {
      public CopyReqMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CopyReqMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CopyReqMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string copyId = 1;
    public static final int COPYID_FIELD_NUMBER = 1;
    private java.lang.Object copyId_;
    /**
     * <code>required string copyId = 1;</code>
     *
     * <pre>
     *副本id
     * </pre>
     */
    public boolean hasCopyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string copyId = 1;</code>
     *
     * <pre>
     *副本id
     * </pre>
     */
    public java.lang.String getCopyId() {
      java.lang.Object ref = copyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          copyId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string copyId = 1;</code>
     *
     * <pre>
     *副本id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCopyIdBytes() {
      java.lang.Object ref = copyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        copyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string code = 2;
    public static final int CODE_FIELD_NUMBER = 2;
    private java.lang.Object code_;
    /**
     * <code>required string code = 2;</code>
     *
     * <pre>
     *校验密码
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string code = 2;</code>
     *
     * <pre>
     *校验密码
     * </pre>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string code = 2;</code>
     *
     * <pre>
     *校验密码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      copyId_ = "";
      code_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCopyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCopyIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCopyIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.BattleVerifyProto.CopyReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.BattleVerifyProto.CopyReqMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BattleVerifyProto.CopyReqMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.BattleVerifyProto.CopyReqMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_CopyReqMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_CopyReqMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.BattleVerifyProto.CopyReqMsg.class, com.rwproto.BattleVerifyProto.CopyReqMsg.Builder.class);
      }

      // Construct using com.rwproto.BattleVerifyProto.CopyReqMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        copyId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_CopyReqMsg_descriptor;
      }

      public com.rwproto.BattleVerifyProto.CopyReqMsg getDefaultInstanceForType() {
        return com.rwproto.BattleVerifyProto.CopyReqMsg.getDefaultInstance();
      }

      public com.rwproto.BattleVerifyProto.CopyReqMsg build() {
        com.rwproto.BattleVerifyProto.CopyReqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.BattleVerifyProto.CopyReqMsg buildPartial() {
        com.rwproto.BattleVerifyProto.CopyReqMsg result = new com.rwproto.BattleVerifyProto.CopyReqMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.copyId_ = copyId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.BattleVerifyProto.CopyReqMsg) {
          return mergeFrom((com.rwproto.BattleVerifyProto.CopyReqMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.BattleVerifyProto.CopyReqMsg other) {
        if (other == com.rwproto.BattleVerifyProto.CopyReqMsg.getDefaultInstance()) return this;
        if (other.hasCopyId()) {
          bitField0_ |= 0x00000001;
          copyId_ = other.copyId_;
          onChanged();
        }
        if (other.hasCode()) {
          bitField0_ |= 0x00000002;
          code_ = other.code_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCopyId()) {
          
          return false;
        }
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.BattleVerifyProto.CopyReqMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.BattleVerifyProto.CopyReqMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string copyId = 1;
      private java.lang.Object copyId_ = "";
      /**
       * <code>required string copyId = 1;</code>
       *
       * <pre>
       *副本id
       * </pre>
       */
      public boolean hasCopyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string copyId = 1;</code>
       *
       * <pre>
       *副本id
       * </pre>
       */
      public java.lang.String getCopyId() {
        java.lang.Object ref = copyId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          copyId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string copyId = 1;</code>
       *
       * <pre>
       *副本id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCopyIdBytes() {
        java.lang.Object ref = copyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          copyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string copyId = 1;</code>
       *
       * <pre>
       *副本id
       * </pre>
       */
      public Builder setCopyId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        copyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string copyId = 1;</code>
       *
       * <pre>
       *副本id
       * </pre>
       */
      public Builder clearCopyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        copyId_ = getDefaultInstance().getCopyId();
        onChanged();
        return this;
      }
      /**
       * <code>required string copyId = 1;</code>
       *
       * <pre>
       *副本id
       * </pre>
       */
      public Builder setCopyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        copyId_ = value;
        onChanged();
        return this;
      }

      // required string code = 2;
      private java.lang.Object code_ = "";
      /**
       * <code>required string code = 2;</code>
       *
       * <pre>
       *校验密码
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string code = 2;</code>
       *
       * <pre>
       *校验密码
       * </pre>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string code = 2;</code>
       *
       * <pre>
       *校验密码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string code = 2;</code>
       *
       * <pre>
       *校验密码
       * </pre>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 2;</code>
       *
       * <pre>
       *校验密码
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 2;</code>
       *
       * <pre>
       *校验密码
       * </pre>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BattleVerifyProto.CopyReqMsg)
    }

    static {
      defaultInstance = new CopyReqMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BattleVerifyProto.CopyReqMsg)
  }

  public interface BattleVerifyComReqMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .BattleVerifyProto.RequestType reqType = 1;
    /**
     * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasReqType();
    /**
     * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
     *
     * <pre>
     * </pre>
     */
    com.rwproto.BattleVerifyProto.RequestType getReqType();

    // optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;
    /**
     * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
     *
     * <pre>
     * </pre>
     */
    boolean hasCopyReqMsg();
    /**
     * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
     *
     * <pre>
     * </pre>
     */
    com.rwproto.BattleVerifyProto.CopyReqMsg getCopyReqMsg();
    /**
     * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
     *
     * <pre>
     * </pre>
     */
    com.rwproto.BattleVerifyProto.CopyReqMsgOrBuilder getCopyReqMsgOrBuilder();
  }
  /**
   * Protobuf type {@code BattleVerifyProto.BattleVerifyComReqMsg}
   */
  public static final class BattleVerifyComReqMsg extends
      com.google.protobuf.GeneratedMessage
      implements BattleVerifyComReqMsgOrBuilder {
    // Use BattleVerifyComReqMsg.newBuilder() to construct.
    private BattleVerifyComReqMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BattleVerifyComReqMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BattleVerifyComReqMsg defaultInstance;
    public static BattleVerifyComReqMsg getDefaultInstance() {
      return defaultInstance;
    }

    public BattleVerifyComReqMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BattleVerifyComReqMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.BattleVerifyProto.RequestType value = com.rwproto.BattleVerifyProto.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                reqType_ = value;
              }
              break;
            }
            case 18: {
              com.rwproto.BattleVerifyProto.CopyReqMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = copyReqMsg_.toBuilder();
              }
              copyReqMsg_ = input.readMessage(com.rwproto.BattleVerifyProto.CopyReqMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(copyReqMsg_);
                copyReqMsg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComReqMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComReqMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg.class, com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<BattleVerifyComReqMsg> PARSER =
        new com.google.protobuf.AbstractParser<BattleVerifyComReqMsg>() {
      public BattleVerifyComReqMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BattleVerifyComReqMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BattleVerifyComReqMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .BattleVerifyProto.RequestType reqType = 1;
    public static final int REQTYPE_FIELD_NUMBER = 1;
    private com.rwproto.BattleVerifyProto.RequestType reqType_;
    /**
     * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasReqType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public com.rwproto.BattleVerifyProto.RequestType getReqType() {
      return reqType_;
    }

    // optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;
    public static final int COPYREQMSG_FIELD_NUMBER = 2;
    private com.rwproto.BattleVerifyProto.CopyReqMsg copyReqMsg_;
    /**
     * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public boolean hasCopyReqMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public com.rwproto.BattleVerifyProto.CopyReqMsg getCopyReqMsg() {
      return copyReqMsg_;
    }
    /**
     * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public com.rwproto.BattleVerifyProto.CopyReqMsgOrBuilder getCopyReqMsgOrBuilder() {
      return copyReqMsg_;
    }

    private void initFields() {
      reqType_ = com.rwproto.BattleVerifyProto.RequestType.Copy;
      copyReqMsg_ = com.rwproto.BattleVerifyProto.CopyReqMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasCopyReqMsg()) {
        if (!getCopyReqMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, copyReqMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, copyReqMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BattleVerifyProto.BattleVerifyComReqMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.BattleVerifyProto.BattleVerifyComReqMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComReqMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComReqMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg.class, com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg.Builder.class);
      }

      // Construct using com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCopyReqMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqType_ = com.rwproto.BattleVerifyProto.RequestType.Copy;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (copyReqMsgBuilder_ == null) {
          copyReqMsg_ = com.rwproto.BattleVerifyProto.CopyReqMsg.getDefaultInstance();
        } else {
          copyReqMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComReqMsg_descriptor;
      }

      public com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg getDefaultInstanceForType() {
        return com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg.getDefaultInstance();
      }

      public com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg build() {
        com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg buildPartial() {
        com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg result = new com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqType_ = reqType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (copyReqMsgBuilder_ == null) {
          result.copyReqMsg_ = copyReqMsg_;
        } else {
          result.copyReqMsg_ = copyReqMsgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg) {
          return mergeFrom((com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg other) {
        if (other == com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg.getDefaultInstance()) return this;
        if (other.hasReqType()) {
          setReqType(other.getReqType());
        }
        if (other.hasCopyReqMsg()) {
          mergeCopyReqMsg(other.getCopyReqMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqType()) {
          
          return false;
        }
        if (hasCopyReqMsg()) {
          if (!getCopyReqMsg().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.BattleVerifyProto.BattleVerifyComReqMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .BattleVerifyProto.RequestType reqType = 1;
      private com.rwproto.BattleVerifyProto.RequestType reqType_ = com.rwproto.BattleVerifyProto.RequestType.Copy;
      /**
       * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasReqType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public com.rwproto.BattleVerifyProto.RequestType getReqType() {
        return reqType_;
      }
      /**
       * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setReqType(com.rwproto.BattleVerifyProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearReqType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqType_ = com.rwproto.BattleVerifyProto.RequestType.Copy;
        onChanged();
        return this;
      }

      // optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;
      private com.rwproto.BattleVerifyProto.CopyReqMsg copyReqMsg_ = com.rwproto.BattleVerifyProto.CopyReqMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.rwproto.BattleVerifyProto.CopyReqMsg, com.rwproto.BattleVerifyProto.CopyReqMsg.Builder, com.rwproto.BattleVerifyProto.CopyReqMsgOrBuilder> copyReqMsgBuilder_;
      /**
       * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public boolean hasCopyReqMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public com.rwproto.BattleVerifyProto.CopyReqMsg getCopyReqMsg() {
        if (copyReqMsgBuilder_ == null) {
          return copyReqMsg_;
        } else {
          return copyReqMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setCopyReqMsg(com.rwproto.BattleVerifyProto.CopyReqMsg value) {
        if (copyReqMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          copyReqMsg_ = value;
          onChanged();
        } else {
          copyReqMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setCopyReqMsg(
          com.rwproto.BattleVerifyProto.CopyReqMsg.Builder builderForValue) {
        if (copyReqMsgBuilder_ == null) {
          copyReqMsg_ = builderForValue.build();
          onChanged();
        } else {
          copyReqMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder mergeCopyReqMsg(com.rwproto.BattleVerifyProto.CopyReqMsg value) {
        if (copyReqMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              copyReqMsg_ != com.rwproto.BattleVerifyProto.CopyReqMsg.getDefaultInstance()) {
            copyReqMsg_ =
              com.rwproto.BattleVerifyProto.CopyReqMsg.newBuilder(copyReqMsg_).mergeFrom(value).buildPartial();
          } else {
            copyReqMsg_ = value;
          }
          onChanged();
        } else {
          copyReqMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearCopyReqMsg() {
        if (copyReqMsgBuilder_ == null) {
          copyReqMsg_ = com.rwproto.BattleVerifyProto.CopyReqMsg.getDefaultInstance();
          onChanged();
        } else {
          copyReqMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public com.rwproto.BattleVerifyProto.CopyReqMsg.Builder getCopyReqMsgBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCopyReqMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
       *
       * <pre>
       * </pre>
       */
      public com.rwproto.BattleVerifyProto.CopyReqMsgOrBuilder getCopyReqMsgOrBuilder() {
        if (copyReqMsgBuilder_ != null) {
          return copyReqMsgBuilder_.getMessageOrBuilder();
        } else {
          return copyReqMsg_;
        }
      }
      /**
       * <code>optional .BattleVerifyProto.CopyReqMsg copyReqMsg = 2;</code>
       *
       * <pre>
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.rwproto.BattleVerifyProto.CopyReqMsg, com.rwproto.BattleVerifyProto.CopyReqMsg.Builder, com.rwproto.BattleVerifyProto.CopyReqMsgOrBuilder> 
          getCopyReqMsgFieldBuilder() {
        if (copyReqMsgBuilder_ == null) {
          copyReqMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.rwproto.BattleVerifyProto.CopyReqMsg, com.rwproto.BattleVerifyProto.CopyReqMsg.Builder, com.rwproto.BattleVerifyProto.CopyReqMsgOrBuilder>(
                  copyReqMsg_,
                  getParentForChildren(),
                  isClean());
          copyReqMsg_ = null;
        }
        return copyReqMsgBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BattleVerifyProto.BattleVerifyComReqMsg)
    }

    static {
      defaultInstance = new BattleVerifyComReqMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BattleVerifyProto.BattleVerifyComReqMsg)
  }

  public interface BattleVerifyComRspMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .BattleVerifyProto.RequestType reqType = 1;
    /**
     * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
     */
    boolean hasReqType();
    /**
     * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
     */
    com.rwproto.BattleVerifyProto.RequestType getReqType();

    // required bool isSuccess = 2;
    /**
     * <code>required bool isSuccess = 2;</code>
     */
    boolean hasIsSuccess();
    /**
     * <code>required bool isSuccess = 2;</code>
     */
    boolean getIsSuccess();

    // optional string tipMsg = 3;
    /**
     * <code>optional string tipMsg = 3;</code>
     */
    boolean hasTipMsg();
    /**
     * <code>optional string tipMsg = 3;</code>
     */
    java.lang.String getTipMsg();
    /**
     * <code>optional string tipMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getTipMsgBytes();
  }
  /**
   * Protobuf type {@code BattleVerifyProto.BattleVerifyComRspMsg}
   */
  public static final class BattleVerifyComRspMsg extends
      com.google.protobuf.GeneratedMessage
      implements BattleVerifyComRspMsgOrBuilder {
    // Use BattleVerifyComRspMsg.newBuilder() to construct.
    private BattleVerifyComRspMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BattleVerifyComRspMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BattleVerifyComRspMsg defaultInstance;
    public static BattleVerifyComRspMsg getDefaultInstance() {
      return defaultInstance;
    }

    public BattleVerifyComRspMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BattleVerifyComRspMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.BattleVerifyProto.RequestType value = com.rwproto.BattleVerifyProto.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                reqType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isSuccess_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              tipMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComRspMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComRspMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg.class, com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<BattleVerifyComRspMsg> PARSER =
        new com.google.protobuf.AbstractParser<BattleVerifyComRspMsg>() {
      public BattleVerifyComRspMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BattleVerifyComRspMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BattleVerifyComRspMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .BattleVerifyProto.RequestType reqType = 1;
    public static final int REQTYPE_FIELD_NUMBER = 1;
    private com.rwproto.BattleVerifyProto.RequestType reqType_;
    /**
     * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
     */
    public boolean hasReqType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
     */
    public com.rwproto.BattleVerifyProto.RequestType getReqType() {
      return reqType_;
    }

    // required bool isSuccess = 2;
    public static final int ISSUCCESS_FIELD_NUMBER = 2;
    private boolean isSuccess_;
    /**
     * <code>required bool isSuccess = 2;</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool isSuccess = 2;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    // optional string tipMsg = 3;
    public static final int TIPMSG_FIELD_NUMBER = 3;
    private java.lang.Object tipMsg_;
    /**
     * <code>optional string tipMsg = 3;</code>
     */
    public boolean hasTipMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string tipMsg = 3;</code>
     */
    public java.lang.String getTipMsg() {
      java.lang.Object ref = tipMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tipMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tipMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTipMsgBytes() {
      java.lang.Object ref = tipMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      reqType_ = com.rwproto.BattleVerifyProto.RequestType.Copy;
      isSuccess_ = false;
      tipMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isSuccess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTipMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isSuccess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTipMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BattleVerifyProto.BattleVerifyComRspMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.BattleVerifyProto.BattleVerifyComRspMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComRspMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComRspMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg.class, com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg.Builder.class);
      }

      // Construct using com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqType_ = com.rwproto.BattleVerifyProto.RequestType.Copy;
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        tipMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.BattleVerifyProto.internal_static_BattleVerifyProto_BattleVerifyComRspMsg_descriptor;
      }

      public com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg getDefaultInstanceForType() {
        return com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg.getDefaultInstance();
      }

      public com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg build() {
        com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg buildPartial() {
        com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg result = new com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqType_ = reqType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tipMsg_ = tipMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg) {
          return mergeFrom((com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg other) {
        if (other == com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg.getDefaultInstance()) return this;
        if (other.hasReqType()) {
          setReqType(other.getReqType());
        }
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasTipMsg()) {
          bitField0_ |= 0x00000004;
          tipMsg_ = other.tipMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqType()) {
          
          return false;
        }
        if (!hasIsSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.BattleVerifyProto.BattleVerifyComRspMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .BattleVerifyProto.RequestType reqType = 1;
      private com.rwproto.BattleVerifyProto.RequestType reqType_ = com.rwproto.BattleVerifyProto.RequestType.Copy;
      /**
       * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
       */
      public boolean hasReqType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
       */
      public com.rwproto.BattleVerifyProto.RequestType getReqType() {
        return reqType_;
      }
      /**
       * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
       */
      public Builder setReqType(com.rwproto.BattleVerifyProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .BattleVerifyProto.RequestType reqType = 1;</code>
       */
      public Builder clearReqType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqType_ = com.rwproto.BattleVerifyProto.RequestType.Copy;
        onChanged();
        return this;
      }

      // required bool isSuccess = 2;
      private boolean isSuccess_ ;
      /**
       * <code>required bool isSuccess = 2;</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool isSuccess = 2;</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>required bool isSuccess = 2;</code>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000002;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSuccess = 2;</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      // optional string tipMsg = 3;
      private java.lang.Object tipMsg_ = "";
      /**
       * <code>optional string tipMsg = 3;</code>
       */
      public boolean hasTipMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       */
      public java.lang.String getTipMsg() {
        java.lang.Object ref = tipMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tipMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTipMsgBytes() {
        java.lang.Object ref = tipMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       */
      public Builder setTipMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tipMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       */
      public Builder clearTipMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tipMsg_ = getDefaultInstance().getTipMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       */
      public Builder setTipMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tipMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BattleVerifyProto.BattleVerifyComRspMsg)
    }

    static {
      defaultInstance = new BattleVerifyComRspMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BattleVerifyProto.BattleVerifyComRspMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BattleVerifyProto_CopyReqMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BattleVerifyProto_CopyReqMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BattleVerifyProto_BattleVerifyComReqMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BattleVerifyProto_BattleVerifyComReqMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BattleVerifyProto_BattleVerifyComRspMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BattleVerifyProto_BattleVerifyComRspMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022BattleVerify.proto\022\021BattleVerifyProto\"" +
      "*\n\nCopyReqMsg\022\016\n\006copyId\030\001 \002(\t\022\014\n\004code\030\002 " +
      "\002(\t\"{\n\025BattleVerifyComReqMsg\022/\n\007reqType\030" +
      "\001 \002(\0162\036.BattleVerifyProto.RequestType\0221\n" +
      "\ncopyReqMsg\030\002 \001(\0132\035.BattleVerifyProto.Co" +
      "pyReqMsg\"k\n\025BattleVerifyComRspMsg\022/\n\007req" +
      "Type\030\001 \002(\0162\036.BattleVerifyProto.RequestTy" +
      "pe\022\021\n\tisSuccess\030\002 \002(\010\022\016\n\006tipMsg\030\003 \001(\t*\027\n" +
      "\013RequestType\022\010\n\004Copy\020\001B \n\013com.rwprotoB\021B" +
      "attleVerifyProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BattleVerifyProto_CopyReqMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BattleVerifyProto_CopyReqMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BattleVerifyProto_CopyReqMsg_descriptor,
              new java.lang.String[] { "CopyId", "Code", });
          internal_static_BattleVerifyProto_BattleVerifyComReqMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BattleVerifyProto_BattleVerifyComReqMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BattleVerifyProto_BattleVerifyComReqMsg_descriptor,
              new java.lang.String[] { "ReqType", "CopyReqMsg", });
          internal_static_BattleVerifyProto_BattleVerifyComRspMsg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_BattleVerifyProto_BattleVerifyComRspMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BattleVerifyProto_BattleVerifyComRspMsg_descriptor,
              new java.lang.String[] { "ReqType", "IsSuccess", "TipMsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
