// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChargeService.proto

package com.rwproto;

public final class ChargeServiceProto {
  private ChargeServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code chargeProto.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Charge = 1;</code>
     *
     * <pre>
     *充值
     * </pre>
     */
    Charge(0, 1),
    /**
     * <code>FirstChargeReward = 2;</code>
     *
     * <pre>
     *领取首充奖励
     * </pre>
     */
    FirstChargeReward(1, 2),
    /**
     * <code>BuyVipGift = 3;</code>
     *
     * <pre>
     *购买VIP礼包
     * </pre>
     */
    BuyVipGift(2, 3),
    /**
     * <code>TimeCard = 4;</code>
     *
     * <pre>
     *购买月卡
     * </pre>
     */
    TimeCard(3, 4),
    ;

    /**
     * <code>Charge = 1;</code>
     *
     * <pre>
     *充值
     * </pre>
     */
    public static final int Charge_VALUE = 1;
    /**
     * <code>FirstChargeReward = 2;</code>
     *
     * <pre>
     *领取首充奖励
     * </pre>
     */
    public static final int FirstChargeReward_VALUE = 2;
    /**
     * <code>BuyVipGift = 3;</code>
     *
     * <pre>
     *购买VIP礼包
     * </pre>
     */
    public static final int BuyVipGift_VALUE = 3;
    /**
     * <code>TimeCard = 4;</code>
     *
     * <pre>
     *购买月卡
     * </pre>
     */
    public static final int TimeCard_VALUE = 4;


    public final int getNumber() { return value; }

    public static RequestType valueOf(int value) {
      switch (value) {
        case 1: return Charge;
        case 2: return FirstChargeReward;
        case 3: return BuyVipGift;
        case 4: return TimeCard;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rwproto.ChargeServiceProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:chargeProto.RequestType)
  }

  public interface ChargeServiceCommonReqMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .chargeProto.RequestType reqType = 1;
    /**
     * <code>required .chargeProto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求功能协议类型
     * </pre>
     */
    boolean hasReqType();
    /**
     * <code>required .chargeProto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求功能协议类型
     * </pre>
     */
    com.rwproto.ChargeServiceProto.RequestType getReqType();

    // required string chargeItemId = 2;
    /**
     * <code>required string chargeItemId = 2;</code>
     *
     * <pre>
     *充值项id
     * </pre>
     */
    boolean hasChargeItemId();
    /**
     * <code>required string chargeItemId = 2;</code>
     *
     * <pre>
     *充值项id
     * </pre>
     */
    java.lang.String getChargeItemId();
    /**
     * <code>required string chargeItemId = 2;</code>
     *
     * <pre>
     *充值项id
     * </pre>
     */
    com.google.protobuf.ByteString
        getChargeItemIdBytes();
  }
  /**
   * Protobuf type {@code chargeProto.ChargeServiceCommonReqMsg}
   */
  public static final class ChargeServiceCommonReqMsg extends
      com.google.protobuf.GeneratedMessage
      implements ChargeServiceCommonReqMsgOrBuilder {
    // Use ChargeServiceCommonReqMsg.newBuilder() to construct.
    private ChargeServiceCommonReqMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChargeServiceCommonReqMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChargeServiceCommonReqMsg defaultInstance;
    public static ChargeServiceCommonReqMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ChargeServiceCommonReqMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChargeServiceCommonReqMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.ChargeServiceProto.RequestType value = com.rwproto.ChargeServiceProto.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                reqType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              chargeItemId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonReqMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonReqMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg.class, com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ChargeServiceCommonReqMsg> PARSER =
        new com.google.protobuf.AbstractParser<ChargeServiceCommonReqMsg>() {
      public ChargeServiceCommonReqMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChargeServiceCommonReqMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChargeServiceCommonReqMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .chargeProto.RequestType reqType = 1;
    public static final int REQTYPE_FIELD_NUMBER = 1;
    private com.rwproto.ChargeServiceProto.RequestType reqType_;
    /**
     * <code>required .chargeProto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求功能协议类型
     * </pre>
     */
    public boolean hasReqType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .chargeProto.RequestType reqType = 1;</code>
     *
     * <pre>
     *请求功能协议类型
     * </pre>
     */
    public com.rwproto.ChargeServiceProto.RequestType getReqType() {
      return reqType_;
    }

    // required string chargeItemId = 2;
    public static final int CHARGEITEMID_FIELD_NUMBER = 2;
    private java.lang.Object chargeItemId_;
    /**
     * <code>required string chargeItemId = 2;</code>
     *
     * <pre>
     *充值项id
     * </pre>
     */
    public boolean hasChargeItemId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string chargeItemId = 2;</code>
     *
     * <pre>
     *充值项id
     * </pre>
     */
    public java.lang.String getChargeItemId() {
      java.lang.Object ref = chargeItemId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chargeItemId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string chargeItemId = 2;</code>
     *
     * <pre>
     *充值项id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChargeItemIdBytes() {
      java.lang.Object ref = chargeItemId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chargeItemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      reqType_ = com.rwproto.ChargeServiceProto.RequestType.Charge;
      chargeItemId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChargeItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getChargeItemIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getChargeItemIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code chargeProto.ChargeServiceCommonReqMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonReqMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonReqMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg.class, com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg.Builder.class);
      }

      // Construct using com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqType_ = com.rwproto.ChargeServiceProto.RequestType.Charge;
        bitField0_ = (bitField0_ & ~0x00000001);
        chargeItemId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonReqMsg_descriptor;
      }

      public com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg getDefaultInstanceForType() {
        return com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg.getDefaultInstance();
      }

      public com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg build() {
        com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg buildPartial() {
        com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg result = new com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqType_ = reqType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.chargeItemId_ = chargeItemId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg) {
          return mergeFrom((com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg other) {
        if (other == com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg.getDefaultInstance()) return this;
        if (other.hasReqType()) {
          setReqType(other.getReqType());
        }
        if (other.hasChargeItemId()) {
          bitField0_ |= 0x00000002;
          chargeItemId_ = other.chargeItemId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqType()) {
          
          return false;
        }
        if (!hasChargeItemId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.ChargeServiceProto.ChargeServiceCommonReqMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .chargeProto.RequestType reqType = 1;
      private com.rwproto.ChargeServiceProto.RequestType reqType_ = com.rwproto.ChargeServiceProto.RequestType.Charge;
      /**
       * <code>required .chargeProto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求功能协议类型
       * </pre>
       */
      public boolean hasReqType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .chargeProto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求功能协议类型
       * </pre>
       */
      public com.rwproto.ChargeServiceProto.RequestType getReqType() {
        return reqType_;
      }
      /**
       * <code>required .chargeProto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求功能协议类型
       * </pre>
       */
      public Builder setReqType(com.rwproto.ChargeServiceProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .chargeProto.RequestType reqType = 1;</code>
       *
       * <pre>
       *请求功能协议类型
       * </pre>
       */
      public Builder clearReqType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqType_ = com.rwproto.ChargeServiceProto.RequestType.Charge;
        onChanged();
        return this;
      }

      // required string chargeItemId = 2;
      private java.lang.Object chargeItemId_ = "";
      /**
       * <code>required string chargeItemId = 2;</code>
       *
       * <pre>
       *充值项id
       * </pre>
       */
      public boolean hasChargeItemId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string chargeItemId = 2;</code>
       *
       * <pre>
       *充值项id
       * </pre>
       */
      public java.lang.String getChargeItemId() {
        java.lang.Object ref = chargeItemId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          chargeItemId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string chargeItemId = 2;</code>
       *
       * <pre>
       *充值项id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChargeItemIdBytes() {
        java.lang.Object ref = chargeItemId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chargeItemId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string chargeItemId = 2;</code>
       *
       * <pre>
       *充值项id
       * </pre>
       */
      public Builder setChargeItemId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        chargeItemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string chargeItemId = 2;</code>
       *
       * <pre>
       *充值项id
       * </pre>
       */
      public Builder clearChargeItemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        chargeItemId_ = getDefaultInstance().getChargeItemId();
        onChanged();
        return this;
      }
      /**
       * <code>required string chargeItemId = 2;</code>
       *
       * <pre>
       *充值项id
       * </pre>
       */
      public Builder setChargeItemIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        chargeItemId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:chargeProto.ChargeServiceCommonReqMsg)
    }

    static {
      defaultInstance = new ChargeServiceCommonReqMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:chargeProto.ChargeServiceCommonReqMsg)
  }

  public interface ChargeServiceCommonRspMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .chargeProto.RequestType reqType = 1;
    /**
     * <code>required .chargeProto.RequestType reqType = 1;</code>
     *
     * <pre>
     *回应的功能协议类型
     * </pre>
     */
    boolean hasReqType();
    /**
     * <code>required .chargeProto.RequestType reqType = 1;</code>
     *
     * <pre>
     *回应的功能协议类型
     * </pre>
     */
    com.rwproto.ChargeServiceProto.RequestType getReqType();

    // required bool isSuccess = 2;
    /**
     * <code>required bool isSuccess = 2;</code>
     *
     * <pre>
     *是否成功处理
     * </pre>
     */
    boolean hasIsSuccess();
    /**
     * <code>required bool isSuccess = 2;</code>
     *
     * <pre>
     *是否成功处理
     * </pre>
     */
    boolean getIsSuccess();

    // optional string tipMsg = 3;
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    boolean hasTipMsg();
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    java.lang.String getTipMsg();
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    com.google.protobuf.ByteString
        getTipMsgBytes();
  }
  /**
   * Protobuf type {@code chargeProto.ChargeServiceCommonRspMsg}
   */
  public static final class ChargeServiceCommonRspMsg extends
      com.google.protobuf.GeneratedMessage
      implements ChargeServiceCommonRspMsgOrBuilder {
    // Use ChargeServiceCommonRspMsg.newBuilder() to construct.
    private ChargeServiceCommonRspMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChargeServiceCommonRspMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChargeServiceCommonRspMsg defaultInstance;
    public static ChargeServiceCommonRspMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ChargeServiceCommonRspMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChargeServiceCommonRspMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.ChargeServiceProto.RequestType value = com.rwproto.ChargeServiceProto.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                reqType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isSuccess_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              tipMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonRspMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonRspMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg.class, com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ChargeServiceCommonRspMsg> PARSER =
        new com.google.protobuf.AbstractParser<ChargeServiceCommonRspMsg>() {
      public ChargeServiceCommonRspMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChargeServiceCommonRspMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChargeServiceCommonRspMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .chargeProto.RequestType reqType = 1;
    public static final int REQTYPE_FIELD_NUMBER = 1;
    private com.rwproto.ChargeServiceProto.RequestType reqType_;
    /**
     * <code>required .chargeProto.RequestType reqType = 1;</code>
     *
     * <pre>
     *回应的功能协议类型
     * </pre>
     */
    public boolean hasReqType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .chargeProto.RequestType reqType = 1;</code>
     *
     * <pre>
     *回应的功能协议类型
     * </pre>
     */
    public com.rwproto.ChargeServiceProto.RequestType getReqType() {
      return reqType_;
    }

    // required bool isSuccess = 2;
    public static final int ISSUCCESS_FIELD_NUMBER = 2;
    private boolean isSuccess_;
    /**
     * <code>required bool isSuccess = 2;</code>
     *
     * <pre>
     *是否成功处理
     * </pre>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool isSuccess = 2;</code>
     *
     * <pre>
     *是否成功处理
     * </pre>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    // optional string tipMsg = 3;
    public static final int TIPMSG_FIELD_NUMBER = 3;
    private java.lang.Object tipMsg_;
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    public boolean hasTipMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    public java.lang.String getTipMsg() {
      java.lang.Object ref = tipMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tipMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tipMsg = 3;</code>
     *
     * <pre>
     *提示消息，可以是成功，也可以是失败的提示消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTipMsgBytes() {
      java.lang.Object ref = tipMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tipMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      reqType_ = com.rwproto.ChargeServiceProto.RequestType.Charge;
      isSuccess_ = false;
      tipMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isSuccess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTipMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isSuccess_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTipMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code chargeProto.ChargeServiceCommonRspMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonRspMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonRspMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg.class, com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg.Builder.class);
      }

      // Construct using com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqType_ = com.rwproto.ChargeServiceProto.RequestType.Charge;
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        tipMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.ChargeServiceProto.internal_static_chargeProto_ChargeServiceCommonRspMsg_descriptor;
      }

      public com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg getDefaultInstanceForType() {
        return com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg.getDefaultInstance();
      }

      public com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg build() {
        com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg buildPartial() {
        com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg result = new com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqType_ = reqType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tipMsg_ = tipMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg) {
          return mergeFrom((com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg other) {
        if (other == com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg.getDefaultInstance()) return this;
        if (other.hasReqType()) {
          setReqType(other.getReqType());
        }
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasTipMsg()) {
          bitField0_ |= 0x00000004;
          tipMsg_ = other.tipMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqType()) {
          
          return false;
        }
        if (!hasIsSuccess()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.ChargeServiceProto.ChargeServiceCommonRspMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .chargeProto.RequestType reqType = 1;
      private com.rwproto.ChargeServiceProto.RequestType reqType_ = com.rwproto.ChargeServiceProto.RequestType.Charge;
      /**
       * <code>required .chargeProto.RequestType reqType = 1;</code>
       *
       * <pre>
       *回应的功能协议类型
       * </pre>
       */
      public boolean hasReqType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .chargeProto.RequestType reqType = 1;</code>
       *
       * <pre>
       *回应的功能协议类型
       * </pre>
       */
      public com.rwproto.ChargeServiceProto.RequestType getReqType() {
        return reqType_;
      }
      /**
       * <code>required .chargeProto.RequestType reqType = 1;</code>
       *
       * <pre>
       *回应的功能协议类型
       * </pre>
       */
      public Builder setReqType(com.rwproto.ChargeServiceProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .chargeProto.RequestType reqType = 1;</code>
       *
       * <pre>
       *回应的功能协议类型
       * </pre>
       */
      public Builder clearReqType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqType_ = com.rwproto.ChargeServiceProto.RequestType.Charge;
        onChanged();
        return this;
      }

      // required bool isSuccess = 2;
      private boolean isSuccess_ ;
      /**
       * <code>required bool isSuccess = 2;</code>
       *
       * <pre>
       *是否成功处理
       * </pre>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool isSuccess = 2;</code>
       *
       * <pre>
       *是否成功处理
       * </pre>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>required bool isSuccess = 2;</code>
       *
       * <pre>
       *是否成功处理
       * </pre>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000002;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSuccess = 2;</code>
       *
       * <pre>
       *是否成功处理
       * </pre>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      // optional string tipMsg = 3;
      private java.lang.Object tipMsg_ = "";
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public boolean hasTipMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public java.lang.String getTipMsg() {
        java.lang.Object ref = tipMsg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tipMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTipMsgBytes() {
        java.lang.Object ref = tipMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tipMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public Builder setTipMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tipMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public Builder clearTipMsg() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tipMsg_ = getDefaultInstance().getTipMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tipMsg = 3;</code>
       *
       * <pre>
       *提示消息，可以是成功，也可以是失败的提示消息
       * </pre>
       */
      public Builder setTipMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        tipMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:chargeProto.ChargeServiceCommonRspMsg)
    }

    static {
      defaultInstance = new ChargeServiceCommonRspMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:chargeProto.ChargeServiceCommonRspMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chargeProto_ChargeServiceCommonReqMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chargeProto_ChargeServiceCommonReqMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chargeProto_ChargeServiceCommonRspMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chargeProto_ChargeServiceCommonRspMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ChargeService.proto\022\013chargeProto\"\\\n\031Ch" +
      "argeServiceCommonReqMsg\022)\n\007reqType\030\001 \002(\016" +
      "2\030.chargeProto.RequestType\022\024\n\014chargeItem" +
      "Id\030\002 \002(\t\"i\n\031ChargeServiceCommonRspMsg\022)\n" +
      "\007reqType\030\001 \002(\0162\030.chargeProto.RequestType" +
      "\022\021\n\tisSuccess\030\002 \002(\010\022\016\n\006tipMsg\030\003 \001(\t*N\n\013R" +
      "equestType\022\n\n\006Charge\020\001\022\025\n\021FirstChargeRew" +
      "ard\020\002\022\016\n\nBuyVipGift\020\003\022\014\n\010TimeCard\020\004B!\n\013c" +
      "om.rwprotoB\022ChargeServiceProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_chargeProto_ChargeServiceCommonReqMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_chargeProto_ChargeServiceCommonReqMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chargeProto_ChargeServiceCommonReqMsg_descriptor,
              new java.lang.String[] { "ReqType", "ChargeItemId", });
          internal_static_chargeProto_ChargeServiceCommonRspMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_chargeProto_ChargeServiceCommonRspMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chargeProto_ChargeServiceCommonRspMsg_descriptor,
              new java.lang.String[] { "ReqType", "IsSuccess", "TipMsg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
