// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TaoistService.proto

package com.rwproto;

public final class TaoistMagicProtos {
  private TaoistMagicProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code TaoistMagic.TaoistRequestType}
   */
  public enum TaoistRequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>getTaoistData = 1;</code>
     *
     * <pre>
     * 获取 道术【id， level】
     * </pre>
     */
    getTaoistData(0, 1),
    /**
     * <code>updateTaoist = 2;</code>
     *
     * <pre>
     *升级道术
     * </pre>
     */
    updateTaoist(1, 2),
    /**
     * <code>getRandom = 3;</code>
     *
     * <pre>
     *获取随机参数，不需要其他参数，返回criticalRamdom
     * </pre>
     */
    getRandom(2, 3),
    ;

    /**
     * <code>getTaoistData = 1;</code>
     *
     * <pre>
     * 获取 道术【id， level】
     * </pre>
     */
    public static final int getTaoistData_VALUE = 1;
    /**
     * <code>updateTaoist = 2;</code>
     *
     * <pre>
     *升级道术
     * </pre>
     */
    public static final int updateTaoist_VALUE = 2;
    /**
     * <code>getRandom = 3;</code>
     *
     * <pre>
     *获取随机参数，不需要其他参数，返回criticalRamdom
     * </pre>
     */
    public static final int getRandom_VALUE = 3;


    public final int getNumber() { return value; }

    public static TaoistRequestType valueOf(int value) {
      switch (value) {
        case 1: return getTaoistData;
        case 2: return updateTaoist;
        case 3: return getRandom;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TaoistRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TaoistRequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TaoistRequestType>() {
            public TaoistRequestType findValueByNumber(int number) {
              return TaoistRequestType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rwproto.TaoistMagicProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final TaoistRequestType[] VALUES = values();

    public static TaoistRequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TaoistRequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TaoistMagic.TaoistRequestType)
  }

  /**
   * Protobuf enum {@code TaoistMagic.ErrorCode_Taoist}
   */
  public enum ErrorCode_Taoist
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Success = 0;</code>
     *
     * <pre>
     * </pre>
     */
    Success(0, 0),
    /**
     * <code>NotEnoughMoney = 1;</code>
     *
     * <pre>
     * </pre>
     */
    NotEnoughMoney(1, 1),
    /**
     * <code>ExceedPlayerLevel = 2;</code>
     *
     * <pre>
     * </pre>
     */
    ExceedPlayerLevel(2, 2),
    ;

    /**
     * <code>Success = 0;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int Success_VALUE = 0;
    /**
     * <code>NotEnoughMoney = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int NotEnoughMoney_VALUE = 1;
    /**
     * <code>ExceedPlayerLevel = 2;</code>
     *
     * <pre>
     * </pre>
     */
    public static final int ExceedPlayerLevel_VALUE = 2;


    public final int getNumber() { return value; }

    public static ErrorCode_Taoist valueOf(int value) {
      switch (value) {
        case 0: return Success;
        case 1: return NotEnoughMoney;
        case 2: return ExceedPlayerLevel;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode_Taoist>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode_Taoist>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode_Taoist>() {
            public ErrorCode_Taoist findValueByNumber(int number) {
              return ErrorCode_Taoist.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.rwproto.TaoistMagicProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final ErrorCode_Taoist[] VALUES = values();

    public static ErrorCode_Taoist valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorCode_Taoist(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TaoistMagic.ErrorCode_Taoist)
  }

  public interface TaoistRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .TaoistMagic.TaoistRequestType reqType = 1;
    /**
     * <code>required .TaoistMagic.TaoistRequestType reqType = 1;</code>
     */
    boolean hasReqType();
    /**
     * <code>required .TaoistMagic.TaoistRequestType reqType = 1;</code>
     */
    com.rwproto.TaoistMagicProtos.TaoistRequestType getReqType();

    // optional int32 taoistId = 2;
    /**
     * <code>optional int32 taoistId = 2;</code>
     *
     * <pre>
     *策划配表(TaoistMagicCfg)的key
     * </pre>
     */
    boolean hasTaoistId();
    /**
     * <code>optional int32 taoistId = 2;</code>
     *
     * <pre>
     *策划配表(TaoistMagicCfg)的key
     * </pre>
     */
    int getTaoistId();

    // optional int32 taoistLevel = 3;
    /**
     * <code>optional int32 taoistLevel = 3;</code>
     *
     * <pre>
     *升级道术目标等级，包含暴击升级
     * </pre>
     */
    boolean hasTaoistLevel();
    /**
     * <code>optional int32 taoistLevel = 3;</code>
     *
     * <pre>
     *升级道术目标等级，包含暴击升级
     * </pre>
     */
    int getTaoistLevel();
  }
  /**
   * Protobuf type {@code TaoistMagic.TaoistRequest}
   */
  public static final class TaoistRequest extends
      com.google.protobuf.GeneratedMessage
      implements TaoistRequestOrBuilder {
    // Use TaoistRequest.newBuilder() to construct.
    private TaoistRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TaoistRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TaoistRequest defaultInstance;
    public static TaoistRequest getDefaultInstance() {
      return defaultInstance;
    }

    public TaoistRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TaoistRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.TaoistMagicProtos.TaoistRequestType value = com.rwproto.TaoistMagicProtos.TaoistRequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                reqType_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              taoistId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              taoistLevel_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.TaoistMagicProtos.TaoistRequest.class, com.rwproto.TaoistMagicProtos.TaoistRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<TaoistRequest> PARSER =
        new com.google.protobuf.AbstractParser<TaoistRequest>() {
      public TaoistRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaoistRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaoistRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .TaoistMagic.TaoistRequestType reqType = 1;
    public static final int REQTYPE_FIELD_NUMBER = 1;
    private com.rwproto.TaoistMagicProtos.TaoistRequestType reqType_;
    /**
     * <code>required .TaoistMagic.TaoistRequestType reqType = 1;</code>
     */
    public boolean hasReqType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .TaoistMagic.TaoistRequestType reqType = 1;</code>
     */
    public com.rwproto.TaoistMagicProtos.TaoistRequestType getReqType() {
      return reqType_;
    }

    // optional int32 taoistId = 2;
    public static final int TAOISTID_FIELD_NUMBER = 2;
    private int taoistId_;
    /**
     * <code>optional int32 taoistId = 2;</code>
     *
     * <pre>
     *策划配表(TaoistMagicCfg)的key
     * </pre>
     */
    public boolean hasTaoistId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 taoistId = 2;</code>
     *
     * <pre>
     *策划配表(TaoistMagicCfg)的key
     * </pre>
     */
    public int getTaoistId() {
      return taoistId_;
    }

    // optional int32 taoistLevel = 3;
    public static final int TAOISTLEVEL_FIELD_NUMBER = 3;
    private int taoistLevel_;
    /**
     * <code>optional int32 taoistLevel = 3;</code>
     *
     * <pre>
     *升级道术目标等级，包含暴击升级
     * </pre>
     */
    public boolean hasTaoistLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 taoistLevel = 3;</code>
     *
     * <pre>
     *升级道术目标等级，包含暴击升级
     * </pre>
     */
    public int getTaoistLevel() {
      return taoistLevel_;
    }

    private void initFields() {
      reqType_ = com.rwproto.TaoistMagicProtos.TaoistRequestType.getTaoistData;
      taoistId_ = 0;
      taoistLevel_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, taoistId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, taoistLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, reqType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, taoistId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, taoistLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.TaoistMagicProtos.TaoistRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaoistMagic.TaoistRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.TaoistMagicProtos.TaoistRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.TaoistMagicProtos.TaoistRequest.class, com.rwproto.TaoistMagicProtos.TaoistRequest.Builder.class);
      }

      // Construct using com.rwproto.TaoistMagicProtos.TaoistRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        reqType_ = com.rwproto.TaoistMagicProtos.TaoistRequestType.getTaoistData;
        bitField0_ = (bitField0_ & ~0x00000001);
        taoistId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        taoistLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistRequest_descriptor;
      }

      public com.rwproto.TaoistMagicProtos.TaoistRequest getDefaultInstanceForType() {
        return com.rwproto.TaoistMagicProtos.TaoistRequest.getDefaultInstance();
      }

      public com.rwproto.TaoistMagicProtos.TaoistRequest build() {
        com.rwproto.TaoistMagicProtos.TaoistRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.TaoistMagicProtos.TaoistRequest buildPartial() {
        com.rwproto.TaoistMagicProtos.TaoistRequest result = new com.rwproto.TaoistMagicProtos.TaoistRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqType_ = reqType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.taoistId_ = taoistId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.taoistLevel_ = taoistLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.TaoistMagicProtos.TaoistRequest) {
          return mergeFrom((com.rwproto.TaoistMagicProtos.TaoistRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.TaoistMagicProtos.TaoistRequest other) {
        if (other == com.rwproto.TaoistMagicProtos.TaoistRequest.getDefaultInstance()) return this;
        if (other.hasReqType()) {
          setReqType(other.getReqType());
        }
        if (other.hasTaoistId()) {
          setTaoistId(other.getTaoistId());
        }
        if (other.hasTaoistLevel()) {
          setTaoistLevel(other.getTaoistLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.TaoistMagicProtos.TaoistRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.TaoistMagicProtos.TaoistRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .TaoistMagic.TaoistRequestType reqType = 1;
      private com.rwproto.TaoistMagicProtos.TaoistRequestType reqType_ = com.rwproto.TaoistMagicProtos.TaoistRequestType.getTaoistData;
      /**
       * <code>required .TaoistMagic.TaoistRequestType reqType = 1;</code>
       */
      public boolean hasReqType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .TaoistMagic.TaoistRequestType reqType = 1;</code>
       */
      public com.rwproto.TaoistMagicProtos.TaoistRequestType getReqType() {
        return reqType_;
      }
      /**
       * <code>required .TaoistMagic.TaoistRequestType reqType = 1;</code>
       */
      public Builder setReqType(com.rwproto.TaoistMagicProtos.TaoistRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .TaoistMagic.TaoistRequestType reqType = 1;</code>
       */
      public Builder clearReqType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqType_ = com.rwproto.TaoistMagicProtos.TaoistRequestType.getTaoistData;
        onChanged();
        return this;
      }

      // optional int32 taoistId = 2;
      private int taoistId_ ;
      /**
       * <code>optional int32 taoistId = 2;</code>
       *
       * <pre>
       *策划配表(TaoistMagicCfg)的key
       * </pre>
       */
      public boolean hasTaoistId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 taoistId = 2;</code>
       *
       * <pre>
       *策划配表(TaoistMagicCfg)的key
       * </pre>
       */
      public int getTaoistId() {
        return taoistId_;
      }
      /**
       * <code>optional int32 taoistId = 2;</code>
       *
       * <pre>
       *策划配表(TaoistMagicCfg)的key
       * </pre>
       */
      public Builder setTaoistId(int value) {
        bitField0_ |= 0x00000002;
        taoistId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 taoistId = 2;</code>
       *
       * <pre>
       *策划配表(TaoistMagicCfg)的key
       * </pre>
       */
      public Builder clearTaoistId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taoistId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 taoistLevel = 3;
      private int taoistLevel_ ;
      /**
       * <code>optional int32 taoistLevel = 3;</code>
       *
       * <pre>
       *升级道术目标等级，包含暴击升级
       * </pre>
       */
      public boolean hasTaoistLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 taoistLevel = 3;</code>
       *
       * <pre>
       *升级道术目标等级，包含暴击升级
       * </pre>
       */
      public int getTaoistLevel() {
        return taoistLevel_;
      }
      /**
       * <code>optional int32 taoistLevel = 3;</code>
       *
       * <pre>
       *升级道术目标等级，包含暴击升级
       * </pre>
       */
      public Builder setTaoistLevel(int value) {
        bitField0_ |= 0x00000004;
        taoistLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 taoistLevel = 3;</code>
       *
       * <pre>
       *升级道术目标等级，包含暴击升级
       * </pre>
       */
      public Builder clearTaoistLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        taoistLevel_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TaoistMagic.TaoistRequest)
    }

    static {
      defaultInstance = new TaoistRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TaoistMagic.TaoistRequest)
  }

  public interface TaoistResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .TaoistMagic.ErrorCode_Taoist errorCode = 1;
    /**
     * <code>required .TaoistMagic.ErrorCode_Taoist errorCode = 1;</code>
     *
     * <pre>
     *操作结果代码，0表示成功
     * </pre>
     */
    boolean hasErrorCode();
    /**
     * <code>required .TaoistMagic.ErrorCode_Taoist errorCode = 1;</code>
     *
     * <pre>
     *操作结果代码，0表示成功
     * </pre>
     */
    com.rwproto.TaoistMagicProtos.ErrorCode_Taoist getErrorCode();

    // optional string resultTip = 2;
    /**
     * <code>optional string resultTip = 2;</code>
     *
     * <pre>
     *如果可能，服务端会定义一个成功或者失败的提示信息
     * </pre>
     */
    boolean hasResultTip();
    /**
     * <code>optional string resultTip = 2;</code>
     *
     * <pre>
     *如果可能，服务端会定义一个成功或者失败的提示信息
     * </pre>
     */
    java.lang.String getResultTip();
    /**
     * <code>optional string resultTip = 2;</code>
     *
     * <pre>
     *如果可能，服务端会定义一个成功或者失败的提示信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getResultTipBytes();

    // optional int32 criticalRamdom = 3;
    /**
     * <code>optional int32 criticalRamdom = 3;</code>
     *
     * <pre>
     *暴击需要的随机参数
     * </pre>
     */
    boolean hasCriticalRamdom();
    /**
     * <code>optional int32 criticalRamdom = 3;</code>
     *
     * <pre>
     *暴击需要的随机参数
     * </pre>
     */
    int getCriticalRamdom();

    // repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    java.util.List<com.rwproto.TaoistMagicProtos.TaoistInfo> 
        getTaoistInfoListList();
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    com.rwproto.TaoistMagicProtos.TaoistInfo getTaoistInfoList(int index);
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    int getTaoistInfoListCount();
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    java.util.List<? extends com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder> 
        getTaoistInfoListOrBuilderList();
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder getTaoistInfoListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TaoistMagic.TaoistResponse}
   */
  public static final class TaoistResponse extends
      com.google.protobuf.GeneratedMessage
      implements TaoistResponseOrBuilder {
    // Use TaoistResponse.newBuilder() to construct.
    private TaoistResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TaoistResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TaoistResponse defaultInstance;
    public static TaoistResponse getDefaultInstance() {
      return defaultInstance;
    }

    public TaoistResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TaoistResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.rwproto.TaoistMagicProtos.ErrorCode_Taoist value = com.rwproto.TaoistMagicProtos.ErrorCode_Taoist.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                errorCode_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              resultTip_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              criticalRamdom_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                taoistInfoList_ = new java.util.ArrayList<com.rwproto.TaoistMagicProtos.TaoistInfo>();
                mutable_bitField0_ |= 0x00000008;
              }
              taoistInfoList_.add(input.readMessage(com.rwproto.TaoistMagicProtos.TaoistInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          taoistInfoList_ = java.util.Collections.unmodifiableList(taoistInfoList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.TaoistMagicProtos.TaoistResponse.class, com.rwproto.TaoistMagicProtos.TaoistResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<TaoistResponse> PARSER =
        new com.google.protobuf.AbstractParser<TaoistResponse>() {
      public TaoistResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaoistResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaoistResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .TaoistMagic.ErrorCode_Taoist errorCode = 1;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private com.rwproto.TaoistMagicProtos.ErrorCode_Taoist errorCode_;
    /**
     * <code>required .TaoistMagic.ErrorCode_Taoist errorCode = 1;</code>
     *
     * <pre>
     *操作结果代码，0表示成功
     * </pre>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .TaoistMagic.ErrorCode_Taoist errorCode = 1;</code>
     *
     * <pre>
     *操作结果代码，0表示成功
     * </pre>
     */
    public com.rwproto.TaoistMagicProtos.ErrorCode_Taoist getErrorCode() {
      return errorCode_;
    }

    // optional string resultTip = 2;
    public static final int RESULTTIP_FIELD_NUMBER = 2;
    private java.lang.Object resultTip_;
    /**
     * <code>optional string resultTip = 2;</code>
     *
     * <pre>
     *如果可能，服务端会定义一个成功或者失败的提示信息
     * </pre>
     */
    public boolean hasResultTip() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string resultTip = 2;</code>
     *
     * <pre>
     *如果可能，服务端会定义一个成功或者失败的提示信息
     * </pre>
     */
    public java.lang.String getResultTip() {
      java.lang.Object ref = resultTip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultTip_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resultTip = 2;</code>
     *
     * <pre>
     *如果可能，服务端会定义一个成功或者失败的提示信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResultTipBytes() {
      java.lang.Object ref = resultTip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultTip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 criticalRamdom = 3;
    public static final int CRITICALRAMDOM_FIELD_NUMBER = 3;
    private int criticalRamdom_;
    /**
     * <code>optional int32 criticalRamdom = 3;</code>
     *
     * <pre>
     *暴击需要的随机参数
     * </pre>
     */
    public boolean hasCriticalRamdom() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 criticalRamdom = 3;</code>
     *
     * <pre>
     *暴击需要的随机参数
     * </pre>
     */
    public int getCriticalRamdom() {
      return criticalRamdom_;
    }

    // repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;
    public static final int TAOISTINFOLIST_FIELD_NUMBER = 4;
    private java.util.List<com.rwproto.TaoistMagicProtos.TaoistInfo> taoistInfoList_;
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    public java.util.List<com.rwproto.TaoistMagicProtos.TaoistInfo> getTaoistInfoListList() {
      return taoistInfoList_;
    }
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    public java.util.List<? extends com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder> 
        getTaoistInfoListOrBuilderList() {
      return taoistInfoList_;
    }
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    public int getTaoistInfoListCount() {
      return taoistInfoList_.size();
    }
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    public com.rwproto.TaoistMagicProtos.TaoistInfo getTaoistInfoList(int index) {
      return taoistInfoList_.get(index);
    }
    /**
     * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
     */
    public com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder getTaoistInfoListOrBuilder(
        int index) {
      return taoistInfoList_.get(index);
    }

    private void initFields() {
      errorCode_ = com.rwproto.TaoistMagicProtos.ErrorCode_Taoist.Success;
      resultTip_ = "";
      criticalRamdom_ = 0;
      taoistInfoList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasErrorCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTaoistInfoListCount(); i++) {
        if (!getTaoistInfoList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, errorCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResultTipBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, criticalRamdom_);
      }
      for (int i = 0; i < taoistInfoList_.size(); i++) {
        output.writeMessage(4, taoistInfoList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errorCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResultTipBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, criticalRamdom_);
      }
      for (int i = 0; i < taoistInfoList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, taoistInfoList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.TaoistMagicProtos.TaoistResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaoistMagic.TaoistResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.TaoistMagicProtos.TaoistResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.TaoistMagicProtos.TaoistResponse.class, com.rwproto.TaoistMagicProtos.TaoistResponse.Builder.class);
      }

      // Construct using com.rwproto.TaoistMagicProtos.TaoistResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTaoistInfoListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errorCode_ = com.rwproto.TaoistMagicProtos.ErrorCode_Taoist.Success;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultTip_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        criticalRamdom_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (taoistInfoListBuilder_ == null) {
          taoistInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          taoistInfoListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistResponse_descriptor;
      }

      public com.rwproto.TaoistMagicProtos.TaoistResponse getDefaultInstanceForType() {
        return com.rwproto.TaoistMagicProtos.TaoistResponse.getDefaultInstance();
      }

      public com.rwproto.TaoistMagicProtos.TaoistResponse build() {
        com.rwproto.TaoistMagicProtos.TaoistResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.TaoistMagicProtos.TaoistResponse buildPartial() {
        com.rwproto.TaoistMagicProtos.TaoistResponse result = new com.rwproto.TaoistMagicProtos.TaoistResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultTip_ = resultTip_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.criticalRamdom_ = criticalRamdom_;
        if (taoistInfoListBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            taoistInfoList_ = java.util.Collections.unmodifiableList(taoistInfoList_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.taoistInfoList_ = taoistInfoList_;
        } else {
          result.taoistInfoList_ = taoistInfoListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.TaoistMagicProtos.TaoistResponse) {
          return mergeFrom((com.rwproto.TaoistMagicProtos.TaoistResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.TaoistMagicProtos.TaoistResponse other) {
        if (other == com.rwproto.TaoistMagicProtos.TaoistResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasResultTip()) {
          bitField0_ |= 0x00000002;
          resultTip_ = other.resultTip_;
          onChanged();
        }
        if (other.hasCriticalRamdom()) {
          setCriticalRamdom(other.getCriticalRamdom());
        }
        if (taoistInfoListBuilder_ == null) {
          if (!other.taoistInfoList_.isEmpty()) {
            if (taoistInfoList_.isEmpty()) {
              taoistInfoList_ = other.taoistInfoList_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureTaoistInfoListIsMutable();
              taoistInfoList_.addAll(other.taoistInfoList_);
            }
            onChanged();
          }
        } else {
          if (!other.taoistInfoList_.isEmpty()) {
            if (taoistInfoListBuilder_.isEmpty()) {
              taoistInfoListBuilder_.dispose();
              taoistInfoListBuilder_ = null;
              taoistInfoList_ = other.taoistInfoList_;
              bitField0_ = (bitField0_ & ~0x00000008);
              taoistInfoListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTaoistInfoListFieldBuilder() : null;
            } else {
              taoistInfoListBuilder_.addAllMessages(other.taoistInfoList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrorCode()) {
          
          return false;
        }
        for (int i = 0; i < getTaoistInfoListCount(); i++) {
          if (!getTaoistInfoList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.TaoistMagicProtos.TaoistResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.TaoistMagicProtos.TaoistResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .TaoistMagic.ErrorCode_Taoist errorCode = 1;
      private com.rwproto.TaoistMagicProtos.ErrorCode_Taoist errorCode_ = com.rwproto.TaoistMagicProtos.ErrorCode_Taoist.Success;
      /**
       * <code>required .TaoistMagic.ErrorCode_Taoist errorCode = 1;</code>
       *
       * <pre>
       *操作结果代码，0表示成功
       * </pre>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .TaoistMagic.ErrorCode_Taoist errorCode = 1;</code>
       *
       * <pre>
       *操作结果代码，0表示成功
       * </pre>
       */
      public com.rwproto.TaoistMagicProtos.ErrorCode_Taoist getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>required .TaoistMagic.ErrorCode_Taoist errorCode = 1;</code>
       *
       * <pre>
       *操作结果代码，0表示成功
       * </pre>
       */
      public Builder setErrorCode(com.rwproto.TaoistMagicProtos.ErrorCode_Taoist value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .TaoistMagic.ErrorCode_Taoist errorCode = 1;</code>
       *
       * <pre>
       *操作结果代码，0表示成功
       * </pre>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = com.rwproto.TaoistMagicProtos.ErrorCode_Taoist.Success;
        onChanged();
        return this;
      }

      // optional string resultTip = 2;
      private java.lang.Object resultTip_ = "";
      /**
       * <code>optional string resultTip = 2;</code>
       *
       * <pre>
       *如果可能，服务端会定义一个成功或者失败的提示信息
       * </pre>
       */
      public boolean hasResultTip() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string resultTip = 2;</code>
       *
       * <pre>
       *如果可能，服务端会定义一个成功或者失败的提示信息
       * </pre>
       */
      public java.lang.String getResultTip() {
        java.lang.Object ref = resultTip_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          resultTip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resultTip = 2;</code>
       *
       * <pre>
       *如果可能，服务端会定义一个成功或者失败的提示信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResultTipBytes() {
        java.lang.Object ref = resultTip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultTip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resultTip = 2;</code>
       *
       * <pre>
       *如果可能，服务端会定义一个成功或者失败的提示信息
       * </pre>
       */
      public Builder setResultTip(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultTip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultTip = 2;</code>
       *
       * <pre>
       *如果可能，服务端会定义一个成功或者失败的提示信息
       * </pre>
       */
      public Builder clearResultTip() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultTip_ = getDefaultInstance().getResultTip();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultTip = 2;</code>
       *
       * <pre>
       *如果可能，服务端会定义一个成功或者失败的提示信息
       * </pre>
       */
      public Builder setResultTipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultTip_ = value;
        onChanged();
        return this;
      }

      // optional int32 criticalRamdom = 3;
      private int criticalRamdom_ ;
      /**
       * <code>optional int32 criticalRamdom = 3;</code>
       *
       * <pre>
       *暴击需要的随机参数
       * </pre>
       */
      public boolean hasCriticalRamdom() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 criticalRamdom = 3;</code>
       *
       * <pre>
       *暴击需要的随机参数
       * </pre>
       */
      public int getCriticalRamdom() {
        return criticalRamdom_;
      }
      /**
       * <code>optional int32 criticalRamdom = 3;</code>
       *
       * <pre>
       *暴击需要的随机参数
       * </pre>
       */
      public Builder setCriticalRamdom(int value) {
        bitField0_ |= 0x00000004;
        criticalRamdom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 criticalRamdom = 3;</code>
       *
       * <pre>
       *暴击需要的随机参数
       * </pre>
       */
      public Builder clearCriticalRamdom() {
        bitField0_ = (bitField0_ & ~0x00000004);
        criticalRamdom_ = 0;
        onChanged();
        return this;
      }

      // repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;
      private java.util.List<com.rwproto.TaoistMagicProtos.TaoistInfo> taoistInfoList_ =
        java.util.Collections.emptyList();
      private void ensureTaoistInfoListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          taoistInfoList_ = new java.util.ArrayList<com.rwproto.TaoistMagicProtos.TaoistInfo>(taoistInfoList_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.rwproto.TaoistMagicProtos.TaoistInfo, com.rwproto.TaoistMagicProtos.TaoistInfo.Builder, com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder> taoistInfoListBuilder_;

      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public java.util.List<com.rwproto.TaoistMagicProtos.TaoistInfo> getTaoistInfoListList() {
        if (taoistInfoListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(taoistInfoList_);
        } else {
          return taoistInfoListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public int getTaoistInfoListCount() {
        if (taoistInfoListBuilder_ == null) {
          return taoistInfoList_.size();
        } else {
          return taoistInfoListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public com.rwproto.TaoistMagicProtos.TaoistInfo getTaoistInfoList(int index) {
        if (taoistInfoListBuilder_ == null) {
          return taoistInfoList_.get(index);
        } else {
          return taoistInfoListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public Builder setTaoistInfoList(
          int index, com.rwproto.TaoistMagicProtos.TaoistInfo value) {
        if (taoistInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaoistInfoListIsMutable();
          taoistInfoList_.set(index, value);
          onChanged();
        } else {
          taoistInfoListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public Builder setTaoistInfoList(
          int index, com.rwproto.TaoistMagicProtos.TaoistInfo.Builder builderForValue) {
        if (taoistInfoListBuilder_ == null) {
          ensureTaoistInfoListIsMutable();
          taoistInfoList_.set(index, builderForValue.build());
          onChanged();
        } else {
          taoistInfoListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public Builder addTaoistInfoList(com.rwproto.TaoistMagicProtos.TaoistInfo value) {
        if (taoistInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaoistInfoListIsMutable();
          taoistInfoList_.add(value);
          onChanged();
        } else {
          taoistInfoListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public Builder addTaoistInfoList(
          int index, com.rwproto.TaoistMagicProtos.TaoistInfo value) {
        if (taoistInfoListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaoistInfoListIsMutable();
          taoistInfoList_.add(index, value);
          onChanged();
        } else {
          taoistInfoListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public Builder addTaoistInfoList(
          com.rwproto.TaoistMagicProtos.TaoistInfo.Builder builderForValue) {
        if (taoistInfoListBuilder_ == null) {
          ensureTaoistInfoListIsMutable();
          taoistInfoList_.add(builderForValue.build());
          onChanged();
        } else {
          taoistInfoListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public Builder addTaoistInfoList(
          int index, com.rwproto.TaoistMagicProtos.TaoistInfo.Builder builderForValue) {
        if (taoistInfoListBuilder_ == null) {
          ensureTaoistInfoListIsMutable();
          taoistInfoList_.add(index, builderForValue.build());
          onChanged();
        } else {
          taoistInfoListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public Builder addAllTaoistInfoList(
          java.lang.Iterable<? extends com.rwproto.TaoistMagicProtos.TaoistInfo> values) {
        if (taoistInfoListBuilder_ == null) {
          ensureTaoistInfoListIsMutable();
          super.addAll(values, taoistInfoList_);
          onChanged();
        } else {
          taoistInfoListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public Builder clearTaoistInfoList() {
        if (taoistInfoListBuilder_ == null) {
          taoistInfoList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          taoistInfoListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public Builder removeTaoistInfoList(int index) {
        if (taoistInfoListBuilder_ == null) {
          ensureTaoistInfoListIsMutable();
          taoistInfoList_.remove(index);
          onChanged();
        } else {
          taoistInfoListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public com.rwproto.TaoistMagicProtos.TaoistInfo.Builder getTaoistInfoListBuilder(
          int index) {
        return getTaoistInfoListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder getTaoistInfoListOrBuilder(
          int index) {
        if (taoistInfoListBuilder_ == null) {
          return taoistInfoList_.get(index);  } else {
          return taoistInfoListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public java.util.List<? extends com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder> 
           getTaoistInfoListOrBuilderList() {
        if (taoistInfoListBuilder_ != null) {
          return taoistInfoListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(taoistInfoList_);
        }
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public com.rwproto.TaoistMagicProtos.TaoistInfo.Builder addTaoistInfoListBuilder() {
        return getTaoistInfoListFieldBuilder().addBuilder(
            com.rwproto.TaoistMagicProtos.TaoistInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public com.rwproto.TaoistMagicProtos.TaoistInfo.Builder addTaoistInfoListBuilder(
          int index) {
        return getTaoistInfoListFieldBuilder().addBuilder(
            index, com.rwproto.TaoistMagicProtos.TaoistInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .TaoistMagic.TaoistInfo taoistInfoList = 4;</code>
       */
      public java.util.List<com.rwproto.TaoistMagicProtos.TaoistInfo.Builder> 
           getTaoistInfoListBuilderList() {
        return getTaoistInfoListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.rwproto.TaoistMagicProtos.TaoistInfo, com.rwproto.TaoistMagicProtos.TaoistInfo.Builder, com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder> 
          getTaoistInfoListFieldBuilder() {
        if (taoistInfoListBuilder_ == null) {
          taoistInfoListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.rwproto.TaoistMagicProtos.TaoistInfo, com.rwproto.TaoistMagicProtos.TaoistInfo.Builder, com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder>(
                  taoistInfoList_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          taoistInfoList_ = null;
        }
        return taoistInfoListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:TaoistMagic.TaoistResponse)
    }

    static {
      defaultInstance = new TaoistResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TaoistMagic.TaoistResponse)
  }

  public interface TaoistInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 taoistID = 1;
    /**
     * <code>required int32 taoistID = 1;</code>
     */
    boolean hasTaoistID();
    /**
     * <code>required int32 taoistID = 1;</code>
     */
    int getTaoistID();

    // required int32 level = 2;
    /**
     * <code>required int32 level = 2;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 2;</code>
     */
    int getLevel();
  }
  /**
   * Protobuf type {@code TaoistMagic.TaoistInfo}
   */
  public static final class TaoistInfo extends
      com.google.protobuf.GeneratedMessage
      implements TaoistInfoOrBuilder {
    // Use TaoistInfo.newBuilder() to construct.
    private TaoistInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TaoistInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TaoistInfo defaultInstance;
    public static TaoistInfo getDefaultInstance() {
      return defaultInstance;
    }

    public TaoistInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TaoistInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              taoistID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              level_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rwproto.TaoistMagicProtos.TaoistInfo.class, com.rwproto.TaoistMagicProtos.TaoistInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<TaoistInfo> PARSER =
        new com.google.protobuf.AbstractParser<TaoistInfo>() {
      public TaoistInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaoistInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaoistInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 taoistID = 1;
    public static final int TAOISTID_FIELD_NUMBER = 1;
    private int taoistID_;
    /**
     * <code>required int32 taoistID = 1;</code>
     */
    public boolean hasTaoistID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 taoistID = 1;</code>
     */
    public int getTaoistID() {
      return taoistID_;
    }

    // required int32 level = 2;
    public static final int LEVEL_FIELD_NUMBER = 2;
    private int level_;
    /**
     * <code>required int32 level = 2;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 level = 2;</code>
     */
    public int getLevel() {
      return level_;
    }

    private void initFields() {
      taoistID_ = 0;
      level_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTaoistID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, taoistID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, level_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, taoistID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, level_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.rwproto.TaoistMagicProtos.TaoistInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rwproto.TaoistMagicProtos.TaoistInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TaoistMagic.TaoistInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rwproto.TaoistMagicProtos.TaoistInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rwproto.TaoistMagicProtos.TaoistInfo.class, com.rwproto.TaoistMagicProtos.TaoistInfo.Builder.class);
      }

      // Construct using com.rwproto.TaoistMagicProtos.TaoistInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        taoistID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rwproto.TaoistMagicProtos.internal_static_TaoistMagic_TaoistInfo_descriptor;
      }

      public com.rwproto.TaoistMagicProtos.TaoistInfo getDefaultInstanceForType() {
        return com.rwproto.TaoistMagicProtos.TaoistInfo.getDefaultInstance();
      }

      public com.rwproto.TaoistMagicProtos.TaoistInfo build() {
        com.rwproto.TaoistMagicProtos.TaoistInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rwproto.TaoistMagicProtos.TaoistInfo buildPartial() {
        com.rwproto.TaoistMagicProtos.TaoistInfo result = new com.rwproto.TaoistMagicProtos.TaoistInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taoistID_ = taoistID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.level_ = level_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rwproto.TaoistMagicProtos.TaoistInfo) {
          return mergeFrom((com.rwproto.TaoistMagicProtos.TaoistInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rwproto.TaoistMagicProtos.TaoistInfo other) {
        if (other == com.rwproto.TaoistMagicProtos.TaoistInfo.getDefaultInstance()) return this;
        if (other.hasTaoistID()) {
          setTaoistID(other.getTaoistID());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTaoistID()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rwproto.TaoistMagicProtos.TaoistInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rwproto.TaoistMagicProtos.TaoistInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 taoistID = 1;
      private int taoistID_ ;
      /**
       * <code>required int32 taoistID = 1;</code>
       */
      public boolean hasTaoistID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 taoistID = 1;</code>
       */
      public int getTaoistID() {
        return taoistID_;
      }
      /**
       * <code>required int32 taoistID = 1;</code>
       */
      public Builder setTaoistID(int value) {
        bitField0_ |= 0x00000001;
        taoistID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 taoistID = 1;</code>
       */
      public Builder clearTaoistID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taoistID_ = 0;
        onChanged();
        return this;
      }

      // required int32 level = 2;
      private int level_ ;
      /**
       * <code>required int32 level = 2;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 level = 2;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 2;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000002;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 2;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TaoistMagic.TaoistInfo)
    }

    static {
      defaultInstance = new TaoistInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TaoistMagic.TaoistInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TaoistMagic_TaoistRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TaoistMagic_TaoistRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TaoistMagic_TaoistResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TaoistMagic_TaoistResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TaoistMagic_TaoistInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TaoistMagic_TaoistInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023TaoistService.proto\022\013TaoistMagic\"g\n\rTa" +
      "oistRequest\022/\n\007reqType\030\001 \002(\0162\036.TaoistMag" +
      "ic.TaoistRequestType\022\020\n\010taoistId\030\002 \001(\005\022\023" +
      "\n\013taoistLevel\030\003 \001(\005\"\236\001\n\016TaoistResponse\0220" +
      "\n\terrorCode\030\001 \002(\0162\035.TaoistMagic.ErrorCod" +
      "e_Taoist\022\021\n\tresultTip\030\002 \001(\t\022\026\n\016criticalR" +
      "amdom\030\003 \001(\005\022/\n\016taoistInfoList\030\004 \003(\0132\027.Ta" +
      "oistMagic.TaoistInfo\"-\n\nTaoistInfo\022\020\n\010ta" +
      "oistID\030\001 \002(\005\022\r\n\005level\030\002 \002(\005*G\n\021TaoistReq" +
      "uestType\022\021\n\rgetTaoistData\020\001\022\020\n\014updateTao",
      "ist\020\002\022\r\n\tgetRandom\020\003*J\n\020ErrorCode_Taoist" +
      "\022\013\n\007Success\020\000\022\022\n\016NotEnoughMoney\020\001\022\025\n\021Exc" +
      "eedPlayerLevel\020\002B \n\013com.rwprotoB\021TaoistM" +
      "agicProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TaoistMagic_TaoistRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TaoistMagic_TaoistRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TaoistMagic_TaoistRequest_descriptor,
              new java.lang.String[] { "ReqType", "TaoistId", "TaoistLevel", });
          internal_static_TaoistMagic_TaoistResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_TaoistMagic_TaoistResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TaoistMagic_TaoistResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "ResultTip", "CriticalRamdom", "TaoistInfoList", });
          internal_static_TaoistMagic_TaoistInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_TaoistMagic_TaoistInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TaoistMagic_TaoistInfo_descriptor,
              new java.lang.String[] { "TaoistID", "Level", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
