package com.rw.service.redpoint;

/**
 * 红点类型枚举(最好使用客户端的配置表)
 * @author Jamaz
 *
 */
public enum RedPointType {
	
	HOME_WINDOW_HERO,
	HERO_LIST_WINDOW_ROLE,
	HERO_LIST_WINDOW_ROLE_SUMMON,
	ROLE_WINDOW_UPGRADE_STAR,
	ROLE_WINDOW_DRESS_EQUIP,
	ROLE_WINDOW_ADVANCED,
	HOME_WINDOW_FISHING_STAGE,
	FISHING_WINDOW_LOW_LEVEL,
	FISHING_WINDOW_MIDDLE_LEVEL,
	HOME_WINDOW_TASK,
	HOME_WINDOW_DAILY,
	HOME_WINDOW_SIGN_IN,
	HOME_WINWOW_MAIL,
	HOME_WINDOW_SEVER_GIFT,
	HOME_WINDOW_OPEN_GIGT
}
